ministryofjustice/hmpps-community-accommodation-tier-2-ui

integration_tests/pages/index.ts, server/routes/index.test.ts, server/utils/nunjucksSetup.ts, server/views/pages/index.njk
this is a holding for the first page of the site, for demo purposes.
=> Add welcome page

server/app.ts, server/applicationVersion.ts, server/config.ts, server/data/healthCheck.ts, server/data/index.ts, server/data/redisClient.ts, server/data/restClient.ts, server/data/restClientMetricsMiddleware.ts, server/data/tokenStore.ts, server/data/tokenVerification.ts, server/errorHandler.ts, server/monitoring/metricsApp.ts, server/routes/testutils/appSetup.ts, server/sanitisedError.ts, server/services/healthCheck.ts, server/utils/azureAppInsights.ts, server/utils/nunjucksSetup.ts, tsconfig.json
we would like to only check files that we've added (e.g. not included in the moj typescript template) and not check files that are just configuration.
=> Test coverage configuration.

cypress.config.ts, integration_tests/mockApis/applications.ts, integration_tests/pages/apply/new.ts, integration_tests/tests/apply/new.cy.ts, integration_tests/tests/apply/risk.cy.ts, server/@types/ui/index.d.ts, server/config.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/apply/index.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/data/index.ts, server/data/restClient.ts, server/paths/api.ts, server/paths/apply.ts, server/routes/index.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/services/index.ts, server/testutils/factories/application.ts, server/testutils/factories/index.ts, server/testutils/factories/risks.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/new.njk, server/views/applications/pages/risks/risks.njk
This PR allows users to save an application, as well as rendering a list of existing applications to the user on the 'New applications' screen.
=> 214 save an application

integration_tests/pages/apply/fundingInformationPage.ts, integration_tests/tests/apply/view_tasklist.cy.ts, server/form-pages/apply/area-and-funding/fundingInformation.test.ts, server/form-pages/apply/area-and-funding/fundingInformation.ts, server/form-pages/apply/area-and-funding/index.ts, server/i18n/en/errors.json, server/utils/validation.test.ts, server/views/applications/pages/area-and-funding/funding-information.njk
This PR adds various content changes to the funding information task, as requested by the design team.
=> Content changes for funding information task

doc/task_list_system.md
The code to introduce this 'task list system' was introduced here [1] This commit adds documentation with examples of how to use it to build a form, edited from @edavey's spike work here [2] 
[1] https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/80
[2] https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/77
=> Add documentation for task list system

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/ethnicGroupPage.ts, integration_tests/pages/apply/whiteBackgroundPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_ethnic_group_page.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_white_background_page.cy.ts, integration_tests/tests/apply/area_and_funding/funding_information/complete_area_and_funding_section.cy.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/ethnicGroup.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/ethnicGroup.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/index.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexualOrientation.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexualOrientation.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/whiteBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/whiteBackground.ts, server/form-pages/utils/getTaskStatus.test.ts, server/form-pages/utils/getTaskStatus.ts, server/i18n/en/errors.json, server/views/applications/pages/equality-and-diversity-monitoring/ethnic-group.njk, server/views/applications/pages/equality-and-diversity-monitoring/white-background.njk
This PR adds the Ethnic Group page and it's first conditional follow-on page.
We will need to add 4 more pages based on the answers to Ethnic Group:
so have tried to make it easy to slot in those pages. 
e2es here https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/16
=> Ethnic Group and White Background pages 

integration_tests/pages/apply/confirmEligibilityPage.ts, server/form-pages/apply/before-you-start/confirm-eligibility/confirmEligibility.test.ts, server/form-pages/apply/before-you-start/confirm-eligibility/confirmEligibility.ts, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
See [Trello 315](https://trello.com/c/7p4Ga5aX/315-eligibility-eligibility-guidance-from-tasklist-3#comment-64cca9e5d18723ba78adeb4c) and individual commit messages.
=> 315 "Confirm eligibility": copy tweaks

integration_tests/pages/apply/risks-and-needs/physicalHealthPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/physical_health.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.ts, server/views/applications/pages/health-needs/physical-health.njk
In this PR we implement the "Physical health" page in the "Health needs" task:
=> (372) Health task: physical health page

integration_tests/pages/apply/risks-and-needs/mentalHealthPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/mental_health.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts, server/views/applications/pages/health-needs/mental-health.njk
This PR implements the "Mental health" page, 3rd in the sequence of pages in the "Health needs" task.
Note that the final question "Please list any issues they have with taking their medication" is currently treated as optional.
=> (374) Health needs task: mental health page

integration_tests/pages/apply/risks-and-needs/communicationAndLanguagePage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/communication_and_language.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.test.ts, server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.ts, server/views/applications/pages/health-needs/communication-and-language.njk
[Trello 373](https://trello.com/c/6V6oEPu8/373-health-subsection-communication-and-language-needs)
=> (373) "Health needs" task: "Communication and language needs" page

integration_tests/pages/apply/risks-and-needs/brainInjuryPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/brain_injury.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.test.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.ts, server/views/applications/pages/health-needs/brain-injury.njk
[Trello 376](https://trello.com/c/0buA2lHP/376-health-subsection-brain-injury)
This is the 6th out of 7 page in the sequence within the "Health needs" task.
=> (376) "Health needs" task: "brain injury" page

integration_tests/pages/apply/risks-and-needs/learningDifficultiesPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/learning_difficulties.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.test.ts, server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.ts, server/views/applications/pages/health-needs/learning-difficulties.njk
[Trello 375](https://trello.com/c/SmsCqlYJ/375-health-subsection-learning-difficulties-and-neurodiversity)
=> (375) "Health needs" task: "Learning difficulties and neurodiversity" page

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/otherHealthPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/other_health.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/otherHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/otherHealth.ts, server/views/applications/pages/health-needs/other-health.njk
[Trello 377](https://trello.com/c/axvnrIw4/377-health-subsection-other-health)
The final page in the sequence for the "Health needs" task:
=> (377) "Health needs" task: "Other health" page

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/about_the_person/equality_and_diversity/careLeaverPage.ts, integration_tests/pages/apply/about_the_person/equality_and_diversity/maritalStatusPage.ts, integration_tests/pages/apply/about_the_person/equality_and_diversity/militaryVeteranPage.ts, integration_tests/pages/apply/about_the_person/equality_and_diversity/parentalCarerResponsibilitiesPage.ts, integration_tests/pages/apply/applyPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_care_leaver.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_marital_status.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_military_veteran.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_parental_carer_responsibilities.cy.ts, server/@types/ui/index.d.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/careLeaver.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/careLeaver.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/index.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/maritalStatus.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/maritalStatus.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/militaryVeteran.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/militaryVeteran.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/parentalCarerResponsibilities.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/parentalCarerResponsibilities.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.ts, server/i18n/en/errors.json, server/views/applications/pages/equality-and-diversity-monitoring/care-leaver.njk, server/views/applications/pages/equality-and-diversity-monitoring/marital-status.njk, server/views/applications/pages/equality-and-diversity-monitoring/military-veteran.njk, server/views/applications/pages/equality-and-diversity-monitoring/parental-carer-responsibilities.njk
This PR adds the remaining E&D task pages: military veteran, care leaver, carer responsibilities and marital status.
=> Allow user to complete equality and diversity monitoring task

helm_deploy/hmpps-community-accommodation-tier-2-ui/values.yaml
This value should match what's in the dev cloud platform repo:
https://github.com/ministryofjustice/cloud-platform-environments/commit/bd2441a0a552a1c7e0486d576f5874f2756ae87c
=> fix serviceAccountName

server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts
See [Trello 330](https://trello.com/c/Qg994Nnx/330-health-subsection-substance-misuse)
=> "Health needs": Substance misuse tweaks

integration_tests/pages/apply/risks-and-needs/risk-to-self/additionalInformationPage.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/additional_information.cy.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.ts, server/views/applications/pages/risk-to-self/additional-information.njk
This adds the conditional radio field above the text area.
=> add Additional Information page questions

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-to-self/acctDataPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/acctPage.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/acct_data.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.ts, server/utils/dateUtils.test.ts, server/utils/dateUtils.ts, server/views/applications/pages/risk-to-self/acct-data.njk, server/views/applications/pages/risk-to-self/acct.njk
[Trello](https://trello.com/c/rNQIhURr/413-risk-to-self-acct)
Apologies for a bit of a scrappy PR - mopping up the final tweaks to the ACCT flow from the prototype.
* Adding a radio wrapper for the expiry date on an ACCT (is ACCT ongoing? yes/no)
* changing the structure of the summary card renders on `acct.ts` page
* adding an 'add another' button on the ACCT form to take the user back to a blank form.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hm …
=> 413 acct questions

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangementsPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/risk_management_arrangements.cy.ts, server/@types/ui/index.d.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.ts, server/views/applications/pages/layout.njk, server/views/applications/pages/risk-of-serious-harm/_risk-of-serious-harm-screen.njk, server/views/applications/pages/risk-of-serious-harm/risk-management-arrangements.njk
https://trello.com/c/IkDDCcmZ/479-rosh-risk-management-arrangements
The 'Risk management arrangements' question within RoSH.
This has a new pattern for us - checkboxes with a 'none of the above' type option. I've added custom to javascript so that if 'no' is checked, the other options are unchecked and vice versa. It will also wipe any text entered in the 'details' text input, as we do not want to risk accidentally surfacing data that should not be saved or shared.
confirm: …
=> 479 Risk management arrangements

integration_tests/tests/apply/risks_and_needs/risk-to-self/current_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/historical_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/vulnerability.cy.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.ts
The answers in the auto-populated OASyS questions should all be required.
confirm:
=> Risk to self required questions

server/@types/shared/models/ApprovedPremisesApplication.ts, server/@types/shared/models/Cas2Application.ts, server/@types/shared/models/SubmitTemporaryAccommodationApplication.ts, server/@types/shared/models/Task.ts, server/@types/shared/models/TemporaryAccommodationApplication.ts, server/@types/shared/models/UpdatePremises.ts, server/@types/shared/models/UpdateRoom.ts
Updating API types from `generate-types`
=> update API types

integration_tests/fixtures/applicationData.json, integration_tests/pages/page.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/reducing_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/risk_factors.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/risk_to_others.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/reducingRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/reducingRisk.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskFactors.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskFactors.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthers.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthers.ts, server/i18n/en/errors.json, server/views/applications/pages/risk-of-serious-harm/reducing-risk.njk, server/views/applications/pages/risk-of-serious-harm/risk-factors.njk, server/views/applications/pages/risk-of-serious-harm/risk-to-others.njk
* Risk to Others https://trello.com/c/iovTSJ0x/475-rosh-risk-to-others-was-about-the-risk
* Risk factors https://trello.com/c/ssPHg9ak/476-rosh-risk-factors
* Reducing risk https://trello.com/c/KgQgdjaf/477-rosh-reducing-risk-was-risk-circumstances
The three OASyS populated questions from RoSH.
Nothing new is introduced from previous pages, hopefully all straightforward!
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier- …
=> 475 RoSH auto-populated OASyS questions

assets/scss/application.scss, assets/scss/components/_summary-card.scss, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotesDataPage.ts, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotesPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/acctPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/behaviour_notes.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/behaviour_notes_data.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotes.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/index.ts, server/views/applications/pages/risk-of-serious-harm/behaviour-notes-data.njk, server/views/applications/pages/risk-of-serious-harm/behaviour-notes.njk
https://trello.com/c/c1U9s1L1/414-rosh-behaviour-notes-was-prison-notes
prototype: https://cas2-prototypes.herokuapp.com/prototypes/risks-and-needs/rosh/v3/behaviour-notes
not in scope:
* 'change' functionality. I will create a ticket for product backlog
The 'add to list' pattern for RoSH's behaviour notes. Copying what we set up for ACCTs so shouldn't be anything new in here, except for a small tweak to the css to ensure the 'action' on a card is justified to the right.
confirm: …
=> RoSH Add behaviour notes

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/roshSummaryPage.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/views/components/roshWidget/template.njk
https://trello.com/c/dl2n6Ny1/343-rosh-rosh-risk-summary-from-oasys 
I noticed on the `dev` environment that we weren't seeing the risk ratings for data that looks like it had been retrieved (see before screenshot). I think this is because we were not using the right data model for what is returned from the API (`RoshRisks` instead of `RoshRisksEnvelope`). It is a bit hard to test locally because the wiremock endpoint doesn't seem to be working, but looking at the types on the API I think this is the right fix..
Because the values are now a nested object, I've had a go at pulling them out in the `response` function of the page. This might conflict with what you've been planning @patrickjfl 
I've also set the `back` button to return to the Task List.
As part of our continuous deployment …
=> Bugs with RoSH Summary page

integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthersPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/risk_to_others.cy.ts, server/views/applications/pages/risk-of-serious-harm/_risk-of-serious-harm-screen.njk
Link to RoSH summary 
I'm not adding tests for all the RoSH pages as I'm not sure it would provide much value, let me know if you think it needs more! 
confirm:
=> add link to RoSH summary to RoSH pages

integration_tests/pages/apply/list.ts, integration_tests/tests/apply/dashboard.cy.ts, server/@types/ui/index.d.ts, server/controllers/apply/applicationsController.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotes.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/_table.njk, server/views/applications/index.njk
https://trello.com/c/dKjzkp4b/369-view-submitted-applications-dashboard 
Small piece of work to list submitted applications on the dashboard. Includes:
* some refactoring of the functions that generate the table
* some tidying of a couple of pages response functions to make it possible to submit applications and test this manually. @patrickjfl you might be changing those responses anyway for Check Your Answers but just thought I'd pop them in as it was annoying me not being able to submit some applications.
* a little unrelated maintenance because I noticed some tests were missing on BehaviourNotes.
Does not include:
* a 'review answers' view for submitted applications. Click on a submitted application currently takes you to the TaskList.
As part of our continuous deployment strategy we …
=> 360 - submitted applications dashboard

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/reducingRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/reducingRisk.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskFactors.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthers.ts, server/i18n/en/errors.json, server/views/applications/pages/risk-of-serious-harm/risk-management-arrangements.njk
Fixing a few issues picked up in QA
* removing placeholder name
* changing order of errors
* correct wording of an error message
https://trello.com/c/ssPHg9ak/476-rosh-risk-factors
https://trello.com/c/KgQgdjaf/477-rosh-reducing-risk-was-risk-circumstances
https://trello.com/c/iovTSJ0x/475-rosh-risk-to-others-was-about-the-risk
https://trello.com/c/IkDDCcmZ/479-rosh-risk-management-arrangements
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-commu …
=> RoSH QA tweaks

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/apply/offence_and_licence_information/offending-history/anyPreviousConvictionsPage.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, integration_tests/tests/apply/offence_and_licence_information/offending-history/any_previous_convictions.cy.ts, integration_tests/tests/apply/offence_and_licence_information/offending_history/any_previous_convictions.cy.ts, server/form-pages/apply/index.ts, server/form-pages/apply/offence-and-licence-information/index.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.ts, server/form-pages/apply/offence-and-licence-information/offending-history/index.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/offending-history/any-previous-convictions.njk
First page of 'Add offending history'  task - conditional logic to routing to the next page TBC.
Includes a `response` function but this will be removed following @patrickjfl 's refactoring work
confirm:
=> Offence history task - any previous convictions

integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/applyPage.ts, integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/page.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/@types/ui/index.d.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/applications/documentUtils.ts, server/utils/checkYourAnswersUtils.ts, server/utils/dateUtils.test.ts, server/utils/nunjucksSetup.ts, server/views/assess/applications/show.njk, server/views/partials/documentSummaryList.njk
https://trello.com/c/OMQN3QPp/588-nacro-submitted-application-answers
We would like to display the questions and answers of a submitted application to assessors.
The design will match the content rendered in the Check Your Answers page, but will need to be generated from the Application's `document` field (which is the canonical source of truth for the content of a submitted application)
This introduces a new macro/partial to generate the Summary List from the `document` sections and adds it the `show` template for applications for assessors. 
I will shortly be introducing the same macro the [submitted application view for referrers](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/280) as the code is so similar.
I'm a bit concerned about the integration …
=> Assessor views submitted application questions/answers

integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/tests/assess/view_application_overview.cy.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/paths/assess.ts, server/routes/assess.ts, server/views/assess/applications/overview.njk
https://trello.com/c/C3cuBfkw/587-nacro-application-overview
confirm:
=> Submitted application overview page

integration_tests/tests/apply/area_and_funding/funding_information/funding_source.cy.ts, server/form-pages/apply/area-and-funding/funding-information/nationalInsurance.test.ts, server/services/applicationService.test.ts, server/services/applicationService.ts
we have several tasks which have branching logic within them.
E.g. on the funding-source page:
IF I answer personal savings
THEN I am taken to national insurance page
AND I do not see the identification page
or
IF I answer benefits
THEN I am taken to the identification page
If a user returns to the `funding-source` page and changes their answer
from `benefits` to `personalSavings`, then we need to ensure any answers
based on `benefits` are deleted.
Because of the way the page system works, it's tricky to get each page
to automate or handle this logic themselves. We only know what data
needs to be deleted /after/ the page data has been submitted.
I'm hesitant to introduce yet another controller function as we did with
the custom forms[1], because of the boilerplate overhead and the …
=> Delete unnecessary data for Funding Information task 

script/generate-types
We revert the URL used to generate our types to the main branch of the API.
confirm:
=> Update API spec URL

assets/scss/application.scss, integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/views/assess/applications/show.njk, server/views/components/printButton/macro.njk
=> Allow assessor to print PDF of application answers

integration_tests/pages/assess/submittedApplicationPage.ts, server/testutils/factories/index.ts, server/testutils/factories/nomisUser.ts, server/testutils/factories/submittedApplication.ts, server/views/assess/applications/show.njk
=> Add referrer details to NACRO submitted application view

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/about_the_person/address_history/previousAddressPage.ts, integration_tests/tests/apply/about_the_person/address_history/previous_address.cy.ts, server/form-pages/apply/about-the-person/address-history/index.ts, server/form-pages/apply/about-the-person/address-history/previousAddress.test.ts, server/form-pages/apply/about-the-person/address-history/previousAddress.ts, server/form-pages/apply/about-the-person/index.ts, server/form-pages/utils/questions.ts, server/i18n/en/errors.json, server/services/applicationService.test.ts, server/services/applicationService.ts, server/utils/applications/deleteOrphanedData.ts, server/views/applications/pages/address-history/previous-address.njk
Address history task and page.
This includes some tricker features -
1. Conditional data, if I change my answer then my inputs for the hidden fields should be deleted when I save. As the function to delete orphaned data is now very long, I've bunged it into a utilities file but open to suggestions. 
2. A fieldset, so lots of fields that it is seemingly not possible to group under one key, because `Page` classes are not built to accept objects, just key/value pairs. 
confirm: …
=> Address history

integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/about_the_person/equality_and_diversity/willAnswerEqualityQuestionsPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_equality_questions_page.cy.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/willAnswer.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/willAnswer.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/equality-and-diversity-monitoring/will-answer-equality-questions.njk
to reflect current copy and design.
=> Add correct copy to E&D

integration_tests/pages/apply/area_and_funding/funding_information/fundingSourcePage.ts, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/tests/apply/area_and_funding/funding_information/funding_source.cy.ts, integration_tests/tests/apply/before_you_apply/confirm_eligibility/confirm_eligibility_task.cy.ts, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk, server/views/applications/pages/layout.njk
https://trello.com/c/9lcTxunU/450-back-to-tasklist-link
confirm:
=> Back to tasklist link

server/form-pages/utils/questions.ts, server/views/applications/pages/risk-of-serious-harm/additional-risk-information.njk
[Trello card 568](https://trello.com/c/Kq9OkRAx/568-content-tweak-add-incentive-level-to-rosh-additional-risk-information-hint-text)
confirm:
=> Update RoSH additional information hint text

doc/task_list_system.md, integration_tests/pages/apply/area_and_funding/funding_information/fundingSourcePage.ts, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/tests/apply/area_and_funding/funding_information/funding_source.cy.ts, server/@types/ui/index.d.ts, server/controllers/apply/applications/pagesController.test.ts, server/views/applications/pages/layout.njk
…so that ‘task list’ is consistently treated as two words.
confirm:
=> Update task list copy

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/area_and_funding/area_information/SecondPreferredAreaPage.ts, integration_tests/tests/apply/area_and_funding/area_information/second_preferred_area.cy.ts, server/form-pages/apply/area-and-funding/area-information/firstPreferredArea.test.ts, server/form-pages/apply/area-and-funding/area-information/firstPreferredArea.ts, server/form-pages/apply/area-and-funding/area-information/index.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.test.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/_area-information-screen.njk, server/views/applications/pages/area-information/second-preferred-area.njk
* Update question copy for the first preferred area page
* Adds a new page to the apply journey `SecondPreferredArea`
confirm:
=> (578) Introduce second preferred area page

assets/scss/application.scss, assets/scss/components/_status-box.scss, integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/pages/assess/updateApplicationStatusPage.ts, integration_tests/tests/assess/update_application_status.cy.ts, integration_tests/tests/assess/view_application_overview.cy.ts, server/controllers/assess/statusUpdateController.test.ts, server/controllers/assess/statusUpdateController.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/testutils/factories/statusUpdate.ts, server/utils/assessUtils.test.ts, server/views/assess/applications/overview.njk, server/views/assess/statusUpdate/new.njk, wiremock/stubs/application-statuses.json
https://trello.com/c/0QoKoYOJ/624-nacro-status-details-on-application-overview.
Will be ready for review once #309 is merged.
confirm:
=> 624 nacro status details on application overview

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/area_and_funding/area_information/FamilyAccommodationPage.ts, integration_tests/tests/apply/area_and_funding/area_information/family_accommodation.cy.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.test.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.ts, server/form-pages/apply/area-and-funding/area-information/index.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.test.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/_area-information-screen.njk, server/views/applications/pages/area-information/family-accommodation.njk
* Update question copy for the family accommodation page
* Adds a new page to the apply journey FamilyAccommodation
confirm:
=> (580) Add family accommodation

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/offence_and_licence_information/current-offences/currentOffenceDataPage.ts, integration_tests/pages/apply/offence_and_licence_information/current-offences/currentOffencesPage.ts, integration_tests/tests/apply/offence_and_licence_information/current-offences/current_offence_data.cy.ts, integration_tests/tests/apply/offence_and_licence_information/current-offences/current_offences.cy.ts, server/@types/ui/index.d.ts, server/form-pages/apply/offence-and-licence-information/current-offences/currentOffences.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/currentOffences.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.ts, server/form-pages/apply/offence-and-licence-information/current-offences/index.ts, server/form-pages/apply/offence-and-licence-information/index.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/current-offences/current-offence-data.njk, server/views/applications/pages/current-offences/current-offences.njk, server/views/applications/pages/offending-history/offence-history-data.njk
[Trello ticket](https://trello.com/c/GqN6gnPJ/417-current-offence-info-add-a-current-offence)
This PR allows referrers to add current offences to the application.
confirm:
=> Allow a referrer to add current offences

integration_tests/pages/assess/updateApplicationStatusPage.ts, integration_tests/tests/assess/update_application_status.cy.ts, server/controllers/assess/statusUpdateController.test.ts, server/controllers/assess/statusUpdateController.ts, server/views/assess/statusUpdate/new.njk
Minor copy change & addition of a back link and a 'back to application overview' link.
confirm:
=> Status update QA changes

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/area_and_funding/area_information/ExclusionZonesPage.ts, integration_tests/tests/apply/area_and_funding/area_information/exclusion_zones.cy.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.test.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.test.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.ts, server/form-pages/apply/area-and-funding/area-information/index.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.test.ts, server/form-pages/apply/area-and-funding/area-information/secondPreferredArea.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/_area-information-screen.njk, server/views/applications/pages/area-information/exclusion-zones.njk
* Update question copy for the exclusion zones page
* Adds ExclusionZones page to the apply journey
confirm:
=> (576) Add exclusion zones page

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/area_and_funding/area_information/GangAffiliationsPage.ts, integration_tests/tests/apply/area_and_funding/area_information/gang_affiliations.cy.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.test.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.test.ts, server/form-pages/apply/area-and-funding/area-information/familyAccommodation.ts, server/form-pages/apply/area-and-funding/area-information/gangAffiliations.test.ts, server/form-pages/apply/area-and-funding/area-information/gangAffiliations.ts, server/form-pages/apply/area-and-funding/area-information/index.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/_area-information-screen.njk, server/views/applications/pages/area-information/gang-affiliations.njk
* Update question copy for the gang affiliations page
* Adds GangAffiliations page to the apply journey
* Update integration tests
confirm:
=> (579) Add gang affiliations page

integration_tests/fixtures/applicationDocument.json, server/form-pages/utils/questions.ts, server/views/partials/email-templates/drug-alcohol-questions.njk
Copied from PR #340 to avoid persistent problems with .DS_store files added to that branch.
Specify the question is about taking illegal substances in custody to differentiate from an incoming question about substance misuse before custody.
Related to general Trello ticket related to Health changes from a stakeholder review.
confirm:
Should a release fail at any step, you …
=> Copy change - health/substances

integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, server/views/applications/show.njk
=> Introduce print button on referrer’s view submitted application page

integration_tests/pages/apply/offence_and_licence_information/hdc-licence-and-cpp-details/cppDetails.ts, server/views/applications/pages/hdc-licence-and-cpp-details/cpp-details.njk
As spotted by Ben, GDS guidance is to use form input types in these cases.
confirm:
=> Set input types for CPP details form page

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/about_the_person/personal_information/immigrationStatusPage.ts, integration_tests/pages/apply/about_the_person/personal_information/workingMobilePhonePage.ts, integration_tests/tests/apply/about_the_person/personal-information/immigration_status.cy.ts, integration_tests/tests/apply/about_the_person/personal-information/working_mobile_phone.cy.ts, server/form-pages/apply/about-the-person/index.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.test.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.ts, server/form-pages/apply/about-the-person/personal-information/index.ts, server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.test.ts, server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/personal-information/immigration-status.njk, server/views/applications/pages/personal-information/working-mobile-phone.njk
This work adds the personal information task to the apply journey.
This task has a male and female journey comprising the following pages:
Both share:
* Working mobile phone page
* Immigration status page
If the application is female, an additional 2 pages will be presented:
* Details on pregnancy page
* Gender preference for support worker page
This PR focuses on the male journey and the female journey will be built upon this work in a later PR.
confirm: …
=> (456) Add personal info task (Male)

integration_tests/pages/apply/applicationSubmittedPage.ts, integration_tests/tests/apply/submit.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/views/applications/confirm.njk
=> Add application details to submit application confirmation page

server/views/applications/pages/offending-history/offence-history-data.njk
Change inaccurate warning text when user adds a previous offence.
[Trello ticket 710](https://trello.com/c/NhpLqwFD/710-offence-history-content-change-to-warning-text)
confirm:
=> Change warning text for adding a previous offence

server/views/applications/pages/area-information/exclusion-zones.njk
* Replace placeholder name with applicant name on exclusion zones page
confirm:
=> (576) Replace placeholder name with applicant name on exclusion zones page

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/before_you_start/referrer_details/confirmDetailsPage.ts, integration_tests/pages/apply/before_you_start/referrer_details/contactNumberPage.ts, integration_tests/pages/apply/before_you_start/referrer_details/jobTitlePage.ts, integration_tests/tests/apply/before_you_apply/referrer-details/confirm_details.cy.ts, integration_tests/tests/apply/before_you_apply/referrer-details/contact_number.cy.ts, integration_tests/tests/apply/before_you_apply/referrer-details/job_title.cy.ts, server/form-pages/apply/before-you-start/index.ts, server/form-pages/apply/before-you-start/referrer-details/confirmDetails.test.ts, server/form-pages/apply/before-you-start/referrer-details/confirmDetails.ts, server/form-pages/apply/before-you-start/referrer-details/contactNumber.test.ts, server/form-pages/apply/before-you-start/referrer-details/contactNumber.ts, server/form-pages/apply/before-you-start/referrer-details/index.ts, server/form-pages/apply/before-you-start/referrer-details/jobTitle.test.ts, server/form-pages/apply/before-you-start/referrer-details/jobTitle.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/referrer-details/confirm-details.njk, server/views/applications/pages/referrer-details/contact-number.njk, server/views/applications/pages/referrer-details/job-title.njk
[Trello ticket](https://trello.com/c/ImdExPQ8/679-referrer-details)
This PR introduces the 'Add your details' task for referrer details.
I'm not sure how likely it is that we will have Nomis users without email addresses, and at the moment we're doing nothing to handle this possibility, beyond the generic warning message in case of incorrect details. Maybe this is enough 🤷 but anyway thoughts welcome!
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpp …
=> Add referrer details task

server/views/applications/pages/personal-information/immigration-status.njk, server/views/applications/pages/personal-information/working-mobile-phone.njk
Allow specific targeting of elements in e2e tests.
confirm:
=> Add data test IDs for e2e tests

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/before_you_start/check_information_needed/checkInformationNeededPage.ts, integration_tests/tests/apply/before_you_apply/check_information_needed/check_information_needed.cy.ts, integration_tests/tests/apply/before_you_apply/referrer-details/contact_number.cy.ts, server/form-pages/apply/before-you-start/index.ts, server/form-pages/apply/before-you-start/information-needed-from-applicant/checkInformationNeeded.test.ts, server/form-pages/apply/before-you-start/information-needed-from-applicant/checkInformationNeeded.ts, server/form-pages/apply/before-you-start/information-needed-from-applicant/index.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/information-needed-from-applicant/information-needed-from-applicant.njk
[Trello ticket](https://trello.com/c/vvvU0NJs/675-check-information-guidance-page)
Adds the above task. Note that in the absence of guidance on what happens if the user selects 'No', for now this is a normal application task that will still render on the task list as 'complete' in that case.
confirm:
Should a release fail at any step, you as the author should now lead the …
=> Check information needed task

assets/scss/application.scss, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, integration_tests/tests/apply/confirm_applicant_details.cy.ts, integration_tests/tests/apply/find_by_prison_number.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/oasys_import_page.cy.ts, integration_tests/tests/apply/submit.cy.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.ts, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk, server/views/components/printButton/macro.njk
* Add print button
* Add application summary
* Add "back to task list" link
* Printed page styling
confirm:
=> (725) Add print button and application summary to check your answers page

server/views/applications/pages/area-information/exclusion-zones.njk
Tweak exclusion zone details guidance hint text to:
- reduce bracket use where not needed
- change ‘e.g.’ to 'for example' (plain English)
- improve clarity on victim name needed
[Trello ticket 748](https://trello.com/c/q0lRIw9A/748-content-tweak-exclusion-zone-tweak-guidance)
confirm:
fix it …
=> Tweak exclusion zone details guidance

package-lock.json, package.json
On a fresh install I ran `script/setup` and then `npm run test` however I immediately ran into 5 errors. Here’s one of the stack traces:
```
PersonClient › meets the contract for the service
,,npm WARN exec The following package was not found and will be installed: swagger-mock-validator@10.1.4
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/Users/tomh/.npm/_npx/0a1932a806ecc0fd/node_modules/lodash/pullAllWith.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/Users/tomh/.npm/_npx/0a1932a806ecc0fd/node_modules/lodash/fp/pullAt.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open '/Users/tomh/.npm/_npx/0a1932a806ecc0fd/node_modules/lodash/pullAt.js'
npm WARN tar TAR_ENTRY_ERROR ENOENT: no such file or directory, open …
```
=> Install required swagger package

helm_deploy/values-prod.yaml, integration_tests/pages/apply/beforeYouStartPage.ts, server/utils/nunjucksSetup.ts, server/views/applications/before-you-start.njk
https://trello.com/c/EFt2j3Lz
[We've confirmed that the service name should be "Short-Term Accommodation (CAS-2)" in this Slack thread](https://mojdt.slack.com/archives/C04T6SC31HA/p1704812197680799) which specifically [references this as the result of a session in July 2023](https://mojdt.slack.com/archives/C04T6SC31HA/p1686922608645579).
- Add production helm charts, checking that maintenance mode is set to true
- Rename the service name to match the new domain name, this updates the header and page titles
Much of the content uses "CAS-2" in what appears to be a short-hand reference, this remains as it was and reduces the size of this change quite a bit. We attempt to rename only the fuller/longer description of the service and only from the users point of view. We keep all internal …
=> (686) Add production helm charts & rename the service to match

integration_tests/pages/static/privacyNoticePage.ts, integration_tests/tests/static/privacy_notice.cy.ts, server/controllers/staticController.test.ts, server/controllers/staticController.ts, server/paths/static.ts, server/routes/static.ts, server/views/applications/pages/confirm-consent/confirm-consent.njk, server/views/partials/layout.njk, server/views/static/privacy-notice.njk
[Trello ticket](https://trello.com/c/qzRGzf4n/452-content-privacy-notice)
confirm:
=> Privacy notice

server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.test.ts, server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.ts
https://trello.com/c/6qqh79K5
Here we fix a bug where if a person was marked as **not pregnant** then the check your answers page would error out. 
The cause of the error is that it's trying to parse a date when the `dueDate` doesn't exist, so we guard against its absence.
We also attempt to make a small improvement to how `dueDate` is present in some cases but absent in others. In an effort to set up our tests with accurate data we had to unpick what the data was actually meant to be on create and on rendering an already completed page. More info in the commit.
We ran the CYA integration tests locally after changing the fixture/application.json data to:
```
"personal-information": {
"working-mobile-phone": {
"hasWorkingMobilePhone": "no"
},
"immigration-status": {
"immigrationStatus": …
```
=> (773) Application CYA works with not pregnant female who has no due date

integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/oasysImportPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/oasysImportPage.ts, server/views/applications/pages/risk-of-serious-harm/oasys-import.njk, server/views/applications/pages/risk-to-self/oasys-import.njk
‘Date created’ should read ‘date started’, in line with the model key name.
confirm:
=> Update OASys import copy

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/health-needs/substanceMisusePage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/substance_misuse.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/substance-misuse.njk
https://trello.com/c/81KdTvlQ/662-health-new-question-are-they-being-released-with-naloxone
Adds a new question - 'Are they being released with naloxone?' - to the substance misuse page.
confirm:
=> Substance misuse - new naloxone question

helm_deploy/values-preprod.yaml
Reverts ministryofjustice/hmpps-community-accommodation-tier-2-ui#428
It worked after a quick fix:
=> Revert "Turn on maintenance mode in preprod to test it"

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/risks-and-needs/health-needs/mentalHealthPage.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/mental-health.njk
https://trello.com/c/wQ2nvVFN/664-health-new-question-are-they-engaged-with-any-mental-health-services-in-custody
E2E PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/62
Adds new question to the mental health form page.
confirm:
=> Add new mental health question

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/risks-and-needs/health-needs/substanceMisusePage.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/substance-misuse.njk, server/views/partials/email-templates/drug-alcohol-questions.njk
https://trello.com/c/cu68N6TF/661-health-new-question-is-there-an-intention-to-refer-them-to-a-drug-and-alcohol-service-when-they-are-released-and-remove-conditio
E2E PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/63
Adds a new question, 'is there an intention to refer them to a drug and alcohol service when they are released?', with a conditional . Removes the conditional from the previous question about those services in custody.
confirm: …
=> Add new substance misuse question

integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/submissions/submissionPage.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/@types/shared/models/Cas2Application.ts, server/@types/shared/models/Cas2SubmittedApplication.ts, server/@types/shared/models/SubmitCas2Application.ts, server/controllers/apply/applicationsController.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.ts, server/testutils/factories/application.ts, server/testutils/factories/submittedApplication.ts, server/utils/applications/getApplicationData.test.ts, server/utils/applications/getApplicationData.ts, server/utils/applications/managementInfoFromAppData.test.ts, server/utils/applications/managementInfoFromAppData.ts, server/views/applications/show.njk, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk
We want to pull out the contact number entered within the application form as a 'first class' field, in order to highlight it to assessors.
API work to be merged in once this is complete
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1328 
* sending the field as a param when submitting the application
* using shared Application Summary component to add the contact number in
* I've also added [the application ID as it was needed for assessors] as I was in the component already (https://trello.com/c/1l6BNsLO/772-add-application-id-to-assessor-view) 
CYA with added ID
Assessor submitted application with added contact number
Referrer submitted application view with added contact number
ready …
=> Add telephone number as 'first class' field in Application Summary

helm_deploy/values-prod.yaml
We’d like to do a quick test with a real user. We’ll watch the logs to make sure nobody finds the service and creates a referral without us asking.
confirm:
=> Turn off maintenance mode in prod

helm_deploy/values-prod.yaml
The deploy of this failed for the session. We revert ministryofjustice/hmpps-community-accommodation-tier-2-ui#460 until the 29th.
=> Revert "Turn off maintenance mode in prod"

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/risks-and-needs/health-needs/substanceMisusePage.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/substance-misuse.njk
https://trello.com/c/mw06lb7X/660-health-remove-conditional-question-how-often-do-they-take-these-substances-by-what-method-and-how-much
No E2E changes are necessary for this PR
confirm:
=> Remove conditional illegal substances sub question

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/risks-and-needs/health-needs/mentalHealthPage.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/mental-health.njk
https://trello.com/c/jcrnUhy5/666-health-rework-question-are-they-prescribed-any-medication-for-their-mental-health
E2E PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/65
PR to update API seed data: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1358.
Reorganises mental health medication question and follow ups.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tie …
=> Rework mental health medication question

integration_tests/pages/apply/risks-and-needs/health-needs/healthNeedsGuidancePage.ts, server/views/partials/email-templates/introduce-yourself.njk
Update 'introduce yourself template' on health guidance page to make content clearer.
[Trello ticket 712](https://trello.com/c/KjRGe57c/712-update-health-guidance)
confirm:
=> Update health guidance introduce yourself template

server/utils/checkYourAnswersUtils.ts
At an earlier stage of development, this change was introduced to be
able to submit incomplete applications for testing purposes. This no
longer works as we've changed our submission logic so this change
removes this code as it's no longer useful.
confirm:
=> Remove code used to submit incomplete applications

integration_tests/pages/apply/risks-and-needs/health-needs/healthNeedsGuidancePage.ts, server/views/partials/email-templates/health-questions.njk
Update health needs copy and paste template in health needs guidance page to reflect health question changes.
[Jira ticket CAS2-149](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-149)
confirm:
=> Update health guidance health needs template

server/views/partials/email-templates/drug-alcohol-questions.njk
Update substance misuse template on health guidance page to reflect health question changes.
[Jira ticket CAS2-149](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-149)
confirm:
=> Update health guidance substance misuse template

integration_tests/tests/productInfo.cy.ts, server/app.ts, server/middleware/setUpProductInfo.test.ts, server/middleware/setUpProductInfo.ts
https://dsdmoj.atlassian.net/browse/CAS2-3 
This adds an `/info` endpoint for CAS2, which is required in order to share the prison codes for private beta roll out, as [required to have a tile on DPS](https://dsdmoj.atlassian.net/wiki/spaces/ALIGN/pages/4480959439/Adding+changing+services+on+the+common+header+footer+and+the+homepage#Establishment-specific-rollouts).
It should return 
```
{
"activeAgencies": [ ],
}
```
The `activeAgencies` list will in the near future be set as a list of the prison codes we're rolling out to. An empty list is the preferred state for a service that is not yet rolled out.
When we are ready to launch private beta, we can update this list with the codes required, and DPS will be able to pick the information up within an hour.
When looking at the …
=> Add '/info' endpoint

server/utils/checkYourAnswersUtils.ts
When this code was first introduced, it allowed the form to be submitted without having completed all the tasks. After changes to the CYA page and how we submit the form, this code now allows us to view the CYA page without completing all tasks.
In future, the check your answers page will be disabled until all tasks are complete, but until that's implemented, we'll keep this logic in.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accom …
=> Update comment for viewing CYA page

server/utils/assessUtils.test.ts, server/utils/assessUtils.ts, server/views/assess/applications/partials/_timeline.njk
We are in the middle of refining this copy and agreeing with stakeholders what the description copy should be - as we are launching on Monday it's being taken out temporarily to avoid any misunderstandings.
https://dsdmoj.atlassian.net/browse/CAS2-142
confirm:
=> temporarily remove hint text for status updates

server/views/applications/pages/information-needed-from-applicant/information-needed-from-applicant.njk
=> Update information needed copy

helm_deploy/values-prod.yaml
Turn off the maintenance page so we can go-live on the 29th.
confirm:
=> Maintenance page turned off for go-live

integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/oasysImportPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/oasysImportPage.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/utils/checkYourAnswersUtils.ts, server/views/applications/pages/risk-of-serious-harm/oasys-import.njk, server/views/applications/pages/risk-to-self/oasys-import.njk
This reversion brings us back into line with our user research.
confirm:
=> Change OASys created text to OASys started

server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.ts, server/views/applications/pages/current-offences/current-offence-data.njk, server/views/applications/pages/risk-to-self/acct-data.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-173
Adds cancel buttons for ACCT and current offence pages. The current offence button is a bit delicate because that is the first page the user lands on from the task list when they first begin the task. In that case, I assume we don't want to render a cancel button - we only want to after an offence has been added, when there is a 'Current offences' (list) page to redirect them to. So I have added an attribute on that page to check if there is data for the task on the application.
confirm:
Once we've merged it will be …
=> Adds cancel buttons to ACCT and current offence pages

assets/scss/application.scss, assets/scss/components/_submitted-application-panel.scss, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/submissions/submissionPage.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.ts, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/applications/show.njk, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk, server/views/components/printButton/macro.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-131
Adds an application summary panel to the check your answers page and submitted applications pages. 
CYA:
Submitted app (referrer view):
Submitted app (assessor view):
CYA:
Submitted app (referrer view):
Submitted app (assessor view):
confirm:
Should a release fail at …
=> Add application summary panel to view answers pages

assets/scss/components/_submitted-application-panel.scss, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/applications/show.njk, server/views/assess/applications/show.njk
following this conversation https://mojdt.slack.com/archives/C04T6SC31HA/p1707303820635869?thread_ts=1707297874.700219&cid=C04T6SC31HA 
* move applicant details to column 
* add back focus stylings to buttons
confirm:
=> tweaks to submitted applications

assets/scss/components/_status-box.scss, e2e-tests/steps/assess.ts, integration_tests/pages/assess/updateApplicationStatusDetailsPage.ts, integration_tests/pages/page.ts, integration_tests/tests/assess/update_application_status.cy.ts, integration_tests/tests/assess/update_application_status_detail.cy.ts, server/controllers/assess/statusUpdateController.test.ts, server/controllers/assess/statusUpdateController.ts, server/controllers/assess/statusUpdateDetailsController.test.ts, server/controllers/assess/statusUpdateDetailsController.ts, server/controllers/index.ts, server/i18n/en/errors.json, server/paths/assess.ts, server/routes/assess.ts, server/testutils/factories/applicationStatusDetailFactory.ts, server/testutils/factories/applicationStatusFactory.ts, server/testutils/factories/index.ts, server/testutils/factories/statusUpdate.ts, server/testutils/factories/statusUpdateDetail.ts, server/utils/assessUtils.test.ts, server/utils/assessUtils.ts, server/utils/nunjucksSetup.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/assess/statusUpdate/new.njk, server/views/assess/statusUpdateDetails/new.njk, server/views/partials/applicationCurrentStatus.njk, server/views/partials/submittedApplicationDetails.njk, wiremock/stubs/application-statuses.json
[Jira ticket](https://dsdmoj.atlassian.net/browse/CAS2-108?atlOrigin=eyJpIjoiMzEyYWEwYmE0MGIyNGVjOTk0Zjk0N2Y2MTJjYWMyNGYiLCJwIjoiaiJ9)
Assessors require the ability to choose a secondary status when updating
the status of the application. This will allow for more specific
statuses.
* Optionally render `statusDetail` page if the selected `status` contains `statusDetails`
* Update styling for "current status" header
* Set back button URL to overview page if status details is referer
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/6377078/602ef296-6174-4b17-b8c1-b6d078087c91
confirm:
`auditEvent`? (see …
=> (CAS2-108) Introduce status detail form

e2e-tests/tests/01_apply.spec.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/submitted_applications/view_application_overview_as_referrer.cy.ts, integration_tests/tests/assess/view_application_overview.cy.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/partials/_timeline.njk
[Jira ticket](https://dsdmoj.atlassian.net/browse/CAS2-208?atlOrigin=eyJpIjoiODRlNzIwOTlhOTRmNDI2ZGFhNzg3ZmYyMGY3MGQxYjgiLCJwIjoiaiJ9)
We are expanding the timeline component to show different types of
timeline events: Notes, status updates and when an application has been
created.
* Use `application.timelineEvents` in timeline component
* Feature flag `notes` event type
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier- …
=> (CAS2-208) Use timeline events

assets/scss/application.scss, assets/scss/components/_actions-menu.scss, integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/tests/assess/view_application_overview.cy.ts, server/views/assess/applications/overview.njk, server/views/partials/header.njk, server/views/partials/layout.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-232
confirm:
=> Add 'Download as a PDF' button to assessor's application overview page

.eslintrc.json, integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/tests/apply/offence_and_licence_information/offending-history/any_previous_convictions.cy.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.ts, server/form-pages/utils/questions.ts, server/utils/applications/deleteOrphanedData.test.ts, server/utils/applications/deleteOrphanedData.ts, server/views/applications/pages/offending-history/any-previous-convictions.njk
[Jira](https://dsdmoj.atlassian.net/browse/CAS2-227?atlOrigin=eyJpIjoiYmY3M2I5YzlkZmU4NDE1ZWI4MDk0NmNhOGJlODRhNmIiLCJwIjoiaiJ9)
Change options for previous conviction question
* Adds an option
* Changes the answer key for one of the existing options
* Adds hint text to options
confirm:
fix it …
=> (227) Changes to previous convictions question

e2e-tests/steps/offenceAndLicenceInformationSection.ts
=> Update e2e test for unspent convictions question

server/form-pages/apply/area-and-funding/funding-information/alternativeID.test.ts, server/form-pages/apply/area-and-funding/funding-information/alternativeID.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/funding-information/alternative-identification.njk, server/views/applications/pages/funding-information/identification.njk
Jira tickets: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-220 and https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-219
Adds 'No ID available' option on alternative ID page. Also updates styling for headings on ID and alternative ID pages, as well as hint text.
confirm:
Should a release …
=> Add 'No ID available' option on alternative ID page

server/form-pages/apply/about-the-person/address-history/previousAddress.test.ts, server/form-pages/apply/about-the-person/address-history/previousAddress.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/address-history/previous-address.njk
Following feedback from users, the last known address fields are optional. Any data entered will be recorded in CYA, and if none is entered, it will show ‘Not applicable’.
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-315
confirm:
Should a release fail at any …
=> Make ‘last known address’ optional

e2e-tests/steps/admin.ts, integration_tests/pages/dashboardPage.ts, server/controllers/dashboardController.test.ts, server/controllers/dashboardController.ts
Update dashboard heading to add hyphen and title case service name
[Jira ticket CAS2-155](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-155)
confirm:
=> Update dashboard heading

cypress.config.ts, e2e-tests/steps/assess.ts, e2e-tests/tests/03_assess.spec.ts, integration_tests/mockApis/assessments.ts, integration_tests/pages/assess/addAssessmentDetailsPage.ts, integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/tests/assess/add_assessment_details.cy.ts, server/@types/shared/models/UpdateCas2Assessment.ts, server/controllers/assess/assessmentsController.test.ts, server/controllers/assess/assessmentsController.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/controllers/index.ts, server/data/assessmentClient.test.ts, server/data/assessmentClient.ts, server/data/index.ts, server/paths/api.ts, server/paths/assess.ts, server/routes/assess.ts, server/services/assessmentService.test.ts, server/services/assessmentService.ts, server/services/index.ts, server/testutils/factories/index.ts, server/testutils/jest.setup.ts, server/utils/assessmentUtils.test.ts, server/utils/assessmentUtils.ts, server/views/assess/applications/assessments/show.njk, server/views/assess/applications/overview.njk
[JIRA](https://dsdmoj.atlassian.net/browse/CAS2-252?atlOrigin=eyJpIjoiN2NiYTUwYmI1ZmE0NDhlM2JmOTZkNzExMTUxMDM2ZWEiLCJwIjoiaiJ9)
We need to include identifying information about each submitted
application so that it can be included in the email notifications that
are sent to the assessor inbox. Therefore, we are adding a new page for
assessors to enter this information.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier-2- …
=> (252) Introduce assessment details page

helm_deploy/values-test.yaml
Turning the feature flag off for Notes.
This will help us test the feature in an
environment that we can 'freeze' easily before we
go to prod.
confirm:
=> Turn on notes in `test` environment

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotesPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/acctPage.ts, server/utils/checkYourAnswersUtils.test.ts, server/utils/nunjucksSetup.ts, server/views/applications/pages/risk-of-serious-harm/behaviour-notes.njk, server/views/applications/pages/risk-to-self/acct.njk
[Jira ticket CAS2-118](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-118)
Original approach in #577 needed to be tweaked due to double escaping of text on Check your answers page (see commit msg for more details)
According to a recent pen test report:
> The stored XSS vulnerability was discovered within the application creation process, where users could add ACCT details and Behaviour Notes. Arbitrary HTML and JavaScript could be inserted into the information fields which would then be executed within the section's summary.
This PR updates the Behaviour Notes and ACCT pages of the task list to use the `formatLines` function, which has two helpful uses:
1. It escapes any HTML preventing the possibility of rendering script tags (or other HTML) …
=> (CAS2-118) Reduce XSS vulnerabilities (and preserve newlines) on behaviour notes and ACCT pages (take 2)

integration_tests/pages/static/cookiesPolicyPage.ts, integration_tests/tests/static/cookies_policy.cy.ts, server/controllers/staticController.ts, server/paths/static.ts, server/routes/static.ts, server/views/partials/layout.njk, server/views/static/cookies-policy.njk
[Jira ticket CAS2-262](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=5f3a78d6347294003e154580&selectedIssue=CAS2-262)
Adds a cookies policy page to the service to inform users of the cookies used in our service, linked in the footer.
confirm:
fix it as soon as …
=> (CAS2-262) Add cookie policy page

server/views/applications/confirm.njk
Adds the feedback form we have in the banner to the form completion page to generate more feedback.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/CAS2-346)
Added text and link to application confirmation screen
confirm:
=> Added feedback form link to application completion screen

server/views/applications/pages/area-information/_preferred-area.njk
[Jira Ticket](https://dsdmoj.atlassian.net/browse/CAS2-79)
Tiny text edits to match designs
confirm:
=> Minor text edits to local connection text

assets/scss/application.scss, e2e-tests/steps/beforeYouStartSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/before_you_start/hdc-licence-dates/hdcIneligiblePage.ts, integration_tests/pages/apply/before_you_start/hdc-licence-dates/hdcLicenceDates.ts, integration_tests/pages/apply/before_you_start/hdc-licence-dates/hdcWarningPage.ts, integration_tests/tests/apply/before_you_apply/hdc_licence_dates/hdc_licence_dates.cy.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcIneligible.test.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcIneligible.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.test.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcWarning.test.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcWarning.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/index.ts, server/utils/dateUtils.test.ts, server/utils/dateUtils.ts, server/views/applications/pages/hdc-licence-dates/hdc-ineligible.njk, server/views/applications/pages/hdc-licence-dates/hdc-warning.njk
[JIRA](https://dsdmoj.atlassian.net/browse/CAS2-265?atlOrigin=eyJpIjoiYTk2ZWQzODRmNjA0NGYxMDgwMjM3MWJkZDhjYjkyNDMiLCJwIjoiaiJ9)
To address the issue of applications being made too close to the
applicant's conditional release date (CRD) which decreases the chance of
the application being successful, we are adding guidance in the HDC
section in the following scenarios:
* If the current date is within 21 days of the CRD - show warning
* If the current date is within 10 days of the CRD - prevent the
application from being submitted
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/6377078/adb5fecf-5193-4b2b-92df-cb88c680f699
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/6377078/a42cbfec-704e-44f1-8ee2-d192539a8e20
As part …
=> (265) Show HDC warnings

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/apply/offence_and_licence_information/offending-history/offenceHistoryDataPage.ts, integration_tests/pages/apply/offence_and_licence_information/offending-history/offenceHistoryPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/offence_and_licence_information/offending-history/offence_history.cy.ts, integration_tests/tests/apply/offence_and_licence_information/offending-history/offence_history_data.cy.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.ts, server/form-pages/apply/offence-and-licence-information/offending-history/offenceHistory.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/offenceHistory.ts, server/form-pages/utils/questions.ts, server/utils/applications/deleteOrphanedData.test.ts, server/utils/applications/getApplicationData.test.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/applications/pages/offending-history/offence-history-data.njk, server/views/applications/pages/offending-history/offence-history.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-368
Updates offence history task to allow for multiple offences grouped by type.
I have ensured backwards compatibility by ignoring all historic offences without a numberOfOffences in the OffenceHistory form page constructor. This is tested in that page's test file. However, I'm open to suggestions if reviewers think this is not sufficient as a testing strategy.
confirm: …
=> (368) Update offence history

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/health-needs/mentalHealthPage.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/mental-health.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-352
Adds new conditional to mental health page.
confirm:
=> Add new conditional to mental health page

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/health-needs/physicalHealthPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/physical_health.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/physical-health.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-351
Combines two questions on physical health page, following feedback from users.
confirm:
=> Combine two questions on physical health page

e2e-tests/steps/risksAndNeedsSection.ts
The E2E tests are fixed to remove the reflect the combining of two physical health questions.
confirm:
=> Fix E2E tests

e2e-tests/steps/apply.ts, e2e-tests/tests/01_apply.spec.ts, integration_tests/mockApis/applications.ts, integration_tests/mockApis/auth.ts, integration_tests/pages/apply/list.ts, integration_tests/pages/apply/prisonDashboard.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/prison_dashboard.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/testutils/factories/applicationSummary.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/index.njk, server/views/applications/prison-dashboard.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-391
confirm:
=> Add applications table to prison dashboard

e2e-tests/steps/apply.ts, e2e-tests/tests/01_apply.spec.ts, server/config.ts
Temporarily extends feature flag to all environments so we can quickly restrict these if we encounter problems.
confirm:
=> Extend prison dashboard feature flag

server/config.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts, server/views/applications/index.njk
Now that we have a functioning prison dashboard, this PR removes the feature flag to make it accessible to our users.
confirm:
=> Remove prison dashboard feature flag

server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts, server/views/applications/prison-dashboard.njk
CAS2 currently is setup for users with the POM
role to be able to create/read applications. We
have since found that the ROLE_POM is given out to
a broad range of users who may not be POMs - The
[LICENCE_CA role](https://dsdmoj.atlassian.net/wiki/spaces/CVL/pages/3540320445/Users+and+Roles) is more in line with who our
users are, and is also used by HDC services to
perform similar actions that we require. We are
therefore going to add in the LICENCE_CA role and
remove the POM role permissions in stages.
This is the first stage - to allow them to view submitted applications for their prisons.
Having done the work on [the API to allow read
access to LICENCE_CA]( https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1786) this PR allows the users to see the prison dashboard …
=> CAS2-416: Allow Licence CA's to see prison dashboard

package-lock.json, package.json, server/views/applications/pages/risk-to-self/vulnerability.njk
Add new vulnerability guidance in the risk to self section.
[Jira ticket 347](https://dsdmoj.atlassian.net/browse/CAS2-347)
confirm:
=> Add vulnerability guidance to risk to self

integration_tests/pages/apply/risks-and-needs/health-needs/healthNeedsGuidancePage.ts, server/views/applications/pages/health-needs/guidance.njk, server/views/partials/email-templates/mental-health-questions.njk
Add mental health questions to the health guidance template page as it was previously missing from templates available to users.
[Jira ticket 363](https://dsdmoj.atlassian.net/browse/CAS2-363)
confirm:
=> Add mental health guidance template

server/views/applications/pages/risk-to-self/vulnerability.njk
Change vulnerability question size to be consistent with all other questions (should be medium instead of small).
[Jira ticket 432](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-432)
confirm:
=> Change vulnerability question size

server/views/applications/pages/offending-history/any-previous-convictions.njk
Add spent convictions warning guidance previous convictions question so users know how to accurately answer the question about previous convictions.
[Jira ticket 463](https://dsdmoj.atlassian.net/browse/CAS2-463)
confirm:
=> Add spent convictions warning guidance to previous convictions question

server/views/applications/pages/risk-to-self/current-risk.njk, server/views/applications/pages/risk-to-self/historical-risk.njk
Update hint text for current and historical risk to self to help guide users to complete the section with enough information the first time and avoid further information requests. 
[Jira ticket 348](https://dsdmoj.atlassian.net/browse/CAS2-348)
Current risk
Historical risk
Current risk
Historical risk
confirm:
Should a release fail at any step, you as the author should now …
=> Update hint text for current and historical risk to self

integration_tests/pages/static/accessibilityStatementPage.ts, integration_tests/tests/static/accessibility_statement.cy.ts, server/controllers/staticController.test.ts, server/controllers/staticController.ts, server/paths/static.ts, server/routes/static.ts, server/views/partials/layout.njk, server/views/static/accessibility-statement.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-45
confirm:
=> Add accessiility statement

server/views/static/accessibility-statement.njk
Quick update to the accessibility statement
confirm:
=> cas2-487 Updated content on accessibility statement

assets/scss/application.scss, package-lock.json, package.json
=> Update govuk-frontend to v5.4.0

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts
https://ministryofjustice.sentry.io/issues/5423227226/?referrer=slack&notification_uuid=625142dd-5ee9-4c6f-9c97-2c1f9f6c5c29&environment=prod&alert_rule_id=14923360&alert_type=issue
This page was failing after removing a question from
the `communication-and-language` page [1] - any
applications with an answer for that question
would not be able to render the CYA page, because
the question has been removed from
`utils/questions.ts`
To guard against this we can check whether the
question exists in the question schema - if it
does not, that means its been removed from the
questions that we render to users, and it just
won't be rendered on CYA.
As the Submitted Application view/document is
generated from the data on CYA, this also means it will be removed from the document when submitted.
[1] …
=> Check for existence of question in CYA page

integration_tests/fixtures/applicationDataPreviousSchema.json, integration_tests/tests/apply/removed_pages/check_your_answers_with_removed_pages.cy.ts, server/utils/checkYourAnswersUtils.ts
we previously removed [1][2] these changes because we thought they were not needed, but actually they were required to enable the rendering of
applications with now-removed pages, e.g.
'reducing-risk' and 'behaviour-notes'.
Although behaviour notes was removed quite a while ago so that most applications will probably not
have that page anymore, I think still worth
keeping in, until we can maybe tidy up this
process of removing pages.
[1] https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/721/commits/126d5873b95fdebb22606c5e47c12960fc8e2f56
[2] https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/728/commits/8f146048d894ab89ee98f8928c734c1e003a33f6 …
=> re-introduce check for removed form pages

server/app.ts
Sets flash messages om res.locals (single request) rather than res.app.locals (whole app).
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-124
confirm:
=> Set flash messages on request rather than app

e2e-tests/steps/apply.ts, e2e-tests/steps/cancelInProgressApplication.ts, e2e-tests/tests/01_apply_as_pom.spec.ts, integration_tests/mockApis/applications.ts, integration_tests/pages/apply/cancelPage.ts, integration_tests/pages/apply/list.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/cancel_in_progress_application.cy.ts, server/controllers/apply/applications/cancelController.test.ts, server/controllers/apply/applications/cancelController.ts, server/controllers/apply/index.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/paths/api.ts, server/paths/apply.ts, server/routes/apply.ts, server/services/applicationService.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/views/applications/cancel.njk, server/views/applications/index.njk
~~NOT TO BE MERGED until API PR has been https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1917~~ ✅ 
https://dsdmoj.atlassian.net/browse/CAS2-216
As a referrer
I want to have the ability to withdraw an (in-progress) application
So that I can ensure my dashboard remains tidy and clear of any applications started in error
This introduces a new Controller to handle the getting and posting of the form view to cancel.
In UI-land we are calling this functionality 'Cancel' based on previous UCD work - in the API we are calling this 'Abandon' because we want to make it clear that it only applies to in progress applications, and distinguish it from the 'Referral cancelled' Status Update. 
ready to be …
=> Cas2-216: Cancel from dashboard

e2e-tests/steps/areaAndFundingSection.ts, integration_tests/fixtures/applicationDocument.json, integration_tests/tests/apply/area_and_funding/funding_information/funding_source.cy.ts, server/form-pages/apply/area-and-funding/funding-information/fundingInformation.test.ts, server/form-pages/apply/area-and-funding/funding-information/fundingInformation.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/funding-information/funding-source.njk
Based on feedback from assessors, we have updated the funding information options, as well as adding hint text to make clear what the different options mean.
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-162
confirm:
Should a release fail at any step, you as the …
=> Update funding information questions

server/views/applications/pages/address-history/previous-address.njk, server/views/applications/pages/equality-and-diversity-monitoring/asian-background.njk, server/views/applications/pages/equality-and-diversity-monitoring/black-background.njk, server/views/applications/pages/equality-and-diversity-monitoring/care-leaver.njk, server/views/applications/pages/equality-and-diversity-monitoring/disability.njk, server/views/applications/pages/equality-and-diversity-monitoring/ethnic-group.njk, server/views/applications/pages/equality-and-diversity-monitoring/marital-status.njk, server/views/applications/pages/equality-and-diversity-monitoring/military-veteran.njk, server/views/applications/pages/equality-and-diversity-monitoring/mixed-background.njk, server/views/applications/pages/equality-and-diversity-monitoring/other-background.njk, server/views/applications/pages/equality-and-diversity-monitoring/parental-carer-responsibilities.njk, server/views/applications/pages/equality-and-diversity-monitoring/religion.njk, server/views/applications/pages/equality-and-diversity-monitoring/sexual-orientation.njk, server/views/applications/pages/equality-and-diversity-monitoring/white-background.njk, server/views/applications/pages/equality-and-diversity-monitoring/will-answer-equality-questions.njk, server/views/applications/pages/offending-history/any-previous-convictions.njk
https://dsdmoj.atlassian.net/browse/CAS2-451
There should be on visual changes as all of these changes are improving the markup thats being used and helping screenreaders with more context to inform users about the page structure and were issues identified as part of an external accessibility audit
=> CAS2 - 451 radio buttons are not linked to context

package.json, server/middleware/setupRequestParsing.ts, server/middleware/trimInput.test.ts, server/middleware/trimInput.ts
Repeat of previous config added to CAS 1 here https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/2137
=> Trim user input strings

server/views/applications/pages/confirm-consent/confirm-consent.njk, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
https://dsdmoj.atlassian.net/browse/CAS2-460
Visual heading on page is not semantically coded as such
On the Confirm Consent page, there is a prominent text label that reads, "Has Catherine Hettinger given their consent to apply for CAS-2?" While the label has been visually styled to resemble a heading and stand out for sighted users, it has not been semantically coded as a heading level 2 `<h2>` element. As a result, although sighted users benefit from the visual styling to quickly see and understand the significant topics of the page, screen reader users do not receive the same programmatic cues.
This leads to a mismatch between the visual and programmatic experience of the page for users who rely on screen readers to navigate through the page. Moreover, screen reader users often use …
=> Update "confirm consent" legend to be an h2

.circleci/config.yml
=> Fix circleci to pick up artefacts from correct directory

.circleci/config.yml
=> Configure circle ci artefacts

server/views/applications/pages/risk-of-serious-harm/risk-to-others.njk
https://dsdmoj.atlassian.net/browse/CAS-680
confirm:
=> Add guidance on how to complete each "Risk to others" questions

integration_tests/pages/apply/confirmApplicantPage.ts, integration_tests/pages/page.ts, server/form-pages/utils/questions.ts, server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts, server/views/people/partials/personDetails.njk, server/views/static/privacy-notice.njk
https://dsdmoj.atlassian.net/browse/CAS-521
confirm:
=> Replace incorrect instances of term NDelius

server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/exclusion-zones.njk
https://dsdmoj.atlassian.net/browse/CAS-722
confirm:
=> Update exclusion zone content

e2e-tests/steps/areaAndFundingSection.ts
(https://dsdmoj.atlassian.net/browse/CAS-722)
Fix the failing e2e test for exclusion zones.
confirm:
=> Update exclusion label

server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/views/assess/applications/overview.njk
Preparation for https://dsdmoj.atlassian.net/browse/CAS-1242
confirm:
=> Refactor mojMenuButton to use component

server/middleware/setUpStaticResources.ts
This is ancient and before govuk_frontend. Its also not included in package.json
confirm:
=> Remove govuk_frontend_toolkit

server/services/applicationService.ts, server/utils/applications/deleteOrphanedData.ts
The AnyValue class is now generated as Unit, so this has been updated accordingly.
=> Update AnyValue to Unit

server/views/partials/layout.njk
=> Remove link to jquery in the layout.njk

server/views/components/sideNav/macro.njk
https://dsdmoj.atlassian.net/browse/CAS-946
"Contents" should really be heading level 2 and not level 3 as its currently being used between and `h1` and `h2`. Although its less prominent on the page it is the heading for the sidebar navigation. This fix was also recommended as part of an external accessibility audit which raised this issue.
There should be no visual difference.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodatio …
=> CAS-946: Fix document hierarchy

e2e-tests/steps/assess.ts, e2e-tests/tests/03_admin.spec.ts
Changes caused by https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/846
=> Fix failing e2e tests as a result of recent change

assets/scss/application.scss, assets/scss/components/_submitted-application-panel.scss, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/applications/show.njk, server/views/assess/applications/assessments/show.njk, server/views/assess/applications/overview.njk, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk, server/views/components/printButton/macro.njk, server/views/partials/header.njk, server/views/partials/layout.njk
https://dsdmoj.atlassian.net/browse/CAS-947
See individual commits but basically tried to tidy up "Print/Download as PDF" output by using a print stylesheet.
=> CAS-947 PDF title text does not meet contrast ratio requirements

e2e-tests/steps/risksAndNeedsSection.ts, integration_tests/pages/apply/risks_and_needs/risk-to-self/acctDataPage.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.ts, server/views/applications/pages/risk-to-self/acct-data.njk
https://dsdmoj.atlassian.net/browse/CAS-954
confirm:
=> CAS-954 3.4 button labels are not consistent and descriptive enough

integration_tests/pages/apply/risks_and_needs/health-needs/healthNeedsGuidancePage.ts, server/views/applications/pages/health-needs/guidance.njk, server/views/partials/email-templates/drug-alcohol-questions.njk, server/views/partials/email-templates/health-questions.njk, server/views/partials/email-templates/introduce-yourself.njk, server/views/partials/email-templates/mental-health-questions.njk
https://dsdmoj.atlassian.net/browse/CAS-955
A few refactor commits before any changes but the last commit implements all the changes need to improve the accessibility of our "Copy text" functionality
An external accessibility audit, raised an issue with the "Copy text" functionality that we have on the page. It reported that there was no feedback that the action had taken place and lead some to be uncertain that the button has functioned correctly.
What I implemented was to change the Copy text button content from `Copy text` to `Text is copied`. This is change is acknowledged by screenreaders as the button now setup to use `aria-live: assertive`. After 5 seconds the content is reverted back to `Copy text`
https://github.com/user-attachments/assets/615934c1-b156-4d39-a060-48c06ba0ae0c …
=> CAS-955 3.6 no feedback when copy text button is interacted with

package-lock.json, package.json, server/middleware/setUpWebSession.ts
This dependency was removed from HMPPS Typescript template so this commit brings this codebase inline with the template.
See https://github.com/ministryofjustice/hmpps-template-typescript/pull/439
=> Remove UUID dependency

assets/scss/components/_side-nav.scss, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/components/sideNav/macro.njk
https://dsdmoj.atlassian.net/browse/CAS-944
confirm:
=> CAS-944 4.7 pdf navigation jump links display in broken lines

cypress.config.ts, integration_tests/mockApis/auth.ts, integration_tests/pages/apply/risks_and_needs/risk-of-serious-harm/roshSummaryPage.ts, integration_tests/pages/page.ts, integration_tests/tasks/accessibilityViolations.ts, integration_tests/tsconfig.json, package-lock.json, package.json, server/views/applications/pages/offending-history/offence-history.njk, server/views/components/roshWidget/template.njk
https://dsdmoj.atlassian.net/browse/CAS-1009
Setups Axe to run automated accessibility audits as part of our integration testing. Please note that these checks are not done in our e2e tests as this project uses cypress for integration and playwright for e2e, two different testing frameworks.
=> CAS-1009 Add accessibility tests to ci pipeline

assets/scss/application.scss, assets/scss/components/_submitted-application-panel.scss, integration_tests/pages/page.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk
https://dsdmoj.atlassian.net/browse/CAS-1352
Added two navigation links to the top of HPT application view page to only be shown on PDF exports
confirm:
=> CAS-1352 Reintroduce two links on the pdf application export

package-lock.json, package.json, server/app.ts, server/utils/azureAppInsights.ts
- https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/1233
- https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/869
- https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/2369
https://dsdmoj.atlassian.net/browse/CAS-1464
No visual changes but in Application insights the url will be clearer for server side logging by not including the UUID in the url
=> CAS-1464 fe parameterise url that app insights is logging

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/form-pages/utils/index.ts, server/i18n/en/errors.json, server/views/applications/pages/risk-of-serious-harm/summary.njk
=> CAS-1221: Add audit information above the rosh summary table

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.ts
https://dsdmoj.atlassian.net/browse/CAS-1221
Add the "Created by prison offender manager" information along with the CreatedAt date. 
confirm:
=> Add created by POM user information

server/@types/ui/index.d.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.test.ts, server/form-pages/utils/questions.ts, server/testutils/factories/risks.ts
=> Fix capitalisation of `Very High` to `Very high`

server/utils/applications/deleteOrphanedData.test.ts, server/utils/applications/deleteOrphanedData.ts
https://dsdmoj.atlassian.net/browse/CAS-1491
confirm:
=> CAS-1491: Remove old manual rosh data if old OASys question changes

server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/index.njk
https://dsdmoj.atlassian.net/browse/CAS-1430
No visual changes to the user
confirm:
=> Refactor index view and build object in util

server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.test.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.ts
https://dsdmoj.atlassian.net/browse/CAS-1540
confirm:
=> CAS-1540: Change hdc crd date validation to allow upto 12 months

integration_tests/mockApis/applications.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/prison_dashboard.cy.ts, server/@types/ui/index.d.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/views/applications/prison-dashboard.njk
https://dsdmoj.atlassian.net/browse/CAS-1429
confirm:
=> CAS-1429: Prison transfers dashboard for receiving omu

.github/workflows/pipeline.yml, package.json, script/fix-cypress-junit-xml
This pipeline is based off CAS1 https://github.com/ministryofjustice/hmpps-approved-premises-ui/blob/f44b0f2481e1a5138b31d1bd6ba458090672263c/.github/workflows/pipeline.yml
This PR does not remove the  Circle CI config part of the workflow but I will do it shortly after to ensure the integration tests are being run in parallel correctly. For this check we need to have some previously run tests where the changes have been merged to main branch.
=> Add GH Actions for CI

package-lock.json, package.json
Fix all vulnerabilities logged in cas-events channel. I ran the npm security check action and no messages were sent to cas-events https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/actions/runs/14381343284
=> Fix npm packages vulnerabilities

integration_tests/pages/submissions/submissionPage.ts, integration_tests/tests/apply/submitted_applications/view_submitted_application_as_referrer.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/utils/applications/getApplicationSummaryData.test.ts, server/utils/applications/getApplicationSummaryData.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/components/applicationSummary/macro.njk
**JIRA**: https://dsdmoj.atlassian.net/browse/CAS-1586
* In the comment of the JIRA you will see the finalised business logic for the banner
* This PR reworks the changes in this PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/907
* The reason for the rework was because the banner requirements for the normal application case (i.e. the non-transfer application) not being included in the JIRA ticket: https://dsdmoj.atlassian.net/browse/CAS-1538
**For all applications**
_pom allocated_
_not allocated_
**When NOT a transfer application:**
**When IS a transfer application:**
_pom allocated_
_not allocated_ …
=> Rework for application summary banner

integration_tests/pages/assess/submittedApplicationPage.ts, integration_tests/pages/submissions/submissionPage.ts, integration_tests/tests/apply/submitted_applications/view_submitted_application_as_referrer.cy.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/apply/index.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/testutils/factories/application.ts, server/testutils/factories/applicationSummary.ts, server/utils/applications/getApplicationSummaryData.test.ts, server/utils/applications/getApplicationSummaryData.ts, server/views/assess/applications/show.njk
**JIRA**: https://dsdmoj.atlassian.net/browse/CAS-1586
* This PR extends the banner re-work done in this PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/920
* Essentially what we are trying to achieve here is that the banners logic is consistent for all user types and so adding the same functionality for the assessor view for an application
**For all assessor applications**
**For all assessor applications**....
**When NOT a transfer application:**
**When IS a transfer application:**
_pom allocated_
_not allocated_
confirm:
Once we've merged it …
=> Prison transfer banner now supported for Assessor's Application view

package-lock.json, package.json
This fixes [this](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/security/code-scanning/32) security issue.
confirm:
=> Dependency version upgrades

server/views/applications/pages/current-offences/current-offence-data.njk
Preventing double clicking when adding multiple current offences for an application
Fixing a bug seen in production where multiple clicks on the "Save and add another" button resulted in a 500 error
confirm:
=> Preventing double clicking when adding multiple current offences
