ministryofjustice/hmpps-community-accommodation-tier-2-ui

helm_deploy/values-dev.yaml
* add `tlsSecretName` to helm dev values
This allows the certificate to work
* add `allowlist: null`
This will enable non-moj laptops to access the site.
=> Environment setup

doc/architecture/decisions/0001_reuse_existing_cas_projects.md
We've made a lot of decisions about what we're picking and choosing so far from the other CAS projects, this ADR is a way to keep track of those decisions.
=> add ADR about copying other CAS projects

.circleci/config.yml, Dockerfile
Package.json already referenced using version 18:
```
"engines": {
"node": "^18",
```
Now, CircleCI and docker containers will run with version 18.16
[To fix security vulnerability CVE-2022-29458](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-supported-accommodation-ui/60/workflows/ad3d130a-bc4e-40aa-ac9d-a40fba81cddc/jobs/216)
```
$ docker build . -t test-16
$ docker run --rm -v trivy-cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --exit-code 100 --no-progress --severity HIGH,CRITICAL --ignore-unfixed --skip-dirs /usr/local/lib/node_modules/npm --skip-files /app/agent.jar test-16
2023-05-10T13:59:37.632Z        INFO    Vulnerability scanning is enabled
2023-05-10T13:59:37.632Z        INFO    Secret scanning is enabled …
```
=> upgrade to node 18.16

Dockerfile
Adding some new libraries, Pact, Shellcheck, has introduced a bunch of new dependencies, including `node-gyp`, which needs `python3` and `bzip2` to be installed. This should fix the Docker build and allow the containers to be built cleanly again.
=> update dependencies in Docker

integration_tests/tsconfig.json, package-lock.json, package.json
We can now update Typescript - it was previously broken with Cypress for those using `typeRoots` but the fix is to specify the node_modules folder so it can find Cypress.[1]
[1] https://github.com/cypress-io/cypress/issues/26930
=> Update Typescript to 5.1.6

helm_deploy/hmpps-community-accommodation-tier-2-ui/values.yaml, integration_tests/tests/health.cy.ts, integration_tests/tests/login.cy.ts, package-lock.json, package.json, server/app.ts, server/applicationVersion.ts, server/config.ts, server/middleware/setUpHealthChecks.ts, server/middleware/setUpSentry.ts
We will be using Sentry to track errors in the app. We're following the
[same implementation as CAS1 + 2](https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/commit/f4fd6ce072799d559d13c307a05229f35ac19ed7), with slight difference that we do not
[need to use the `@sentry/tracing` package because it is being
deprecated](https://docs.sentry.io/product/sentry-basics/tracing/).
I've tested this out locally by creating an error [and it has been logged here](https://ministryofjustice.sentry.io/issues/4293405489/?project=4505442489729024&referrer=project-issue-stream)
=> Sentry integration

.circleci/config.yml, README.md
This PR adds the CI job to run the e2e tests after the dev environment has been deployed on `main`, and will alert our `hmpps-cas-2-team-events` channel on failure.
Also added link to the e2e repo in the Readme doc.
=> E2E test setup for CI

package.json, server/form-pages/apply/area-and-funding/fundingInformation.test.ts, server/form-pages/utils/getTaskStatus.test.ts, server/form-pages/utils/getTaskStatus.ts, server/form-pages/utils/index.test.ts, server/services/applicationService.test.ts, server/utils/applications/getApplicationData.test.ts, server/utils/dateUtils.ts, server/utils/validation.test.ts, server/utils/validation.ts
When we pulled in the code to [add the task list system](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/80) there were a few unit test gaps.
This PR plugs the gaps, mostly with tests from CAS1, and a few little ones of our own. 
* This also adds `--collectCoverage` to the `test` command. This means passing the 100% coverage will be part of CI, do we want to keep it at 100%?
=> Unit test coverage

integration_tests/pages/page.ts, integration_tests/tests/apply/view_tasklist.cy.ts, server/form-pages/apply/area-and-funding/fundingInformation.test.ts, server/form-pages/apply/area-and-funding/fundingInformation.ts, server/views/applications/pages/layout.njk
This PR copies over the form page back button functionality from CAS-1, which will render a back button to either the task list page or the previous task page, based on what is returned from the previous() method on the form page class.
In the case of the back button, CAS-1 refer to their task list page as a 'dashboard' I have replaced this with 'taskList'.
=> Add back button on form pages

package-lock.json, package.json
The recently upgraded cypress installation (`12.7.1` -> `12.7.2`) has resulted in a [vulnerability warning](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier-2-ui/519/workflows/4ea28190-5859-4266-87de-6c4ff38d402d/jobs/1381)
This is [CWE 1321](https://github.com/advisories?query=cwe%3A1321):
[tough-cookie Prototype Pollution vulnerability](https://github.com/advisories/GHSA-72xf-g2v4-qvf3)
and comes from cypress' `@cypress/request` package
This has not yet been fixed in cypress though there's a PR waiting to be merged:
https://github.com/cypress-io/request/pull/32
We declare a temporary 'override' in `package.json` to force this upgrade.
=> Patch npm package 'tough-cookie' version

.circleci/config.yml, helm_deploy/values-test.yaml
We would like to create a test environment for CAS2 so that we can easily demo features.
The [bootstrap](https://github.com/ministryofjustice/dps-project-bootstrap/pull/468) and [cloud PRs](https://github.com/ministryofjustice/cloud-platform-environments/pull/14813) have been merged.
Like CAS1 and 3, deployment to test will be manual, so that we have control over what features are released there.
=> Add `test` environment configuration

helm_deploy/values-dev.yaml, helm_deploy/values-test.yaml, server/config.ts, server/data/restClient.ts
[Trello 436](https://trello.com/c/LI4W8feo/436-fix-errors-on-api-timeout-when-searching-for-crn) 
There are 2 parts to this, all taken from CAS1's work in:
- https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/981/
- https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/987/
- https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/989/
This was causing multiple applications to be created when a request timed out due to the OASys API being unavailable.
The timeout between the frontend and the backend must  be greater than the timeout between the API and the
OASys Context API (which are both currently 10 seconds.)
=> 436 fix errors on API timeout when searching for CRN

integration_tests/pages/apply/list.ts, server/@types/shared/models/Cas2ApplicationSummary.ts, server/@types/ui/index.d.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/dateUtils.ts, server/views/applications/_table.njk, server/views/applications/index.njk
we would like to be able to render applications a user has
created, and indicate the ones that are still in progress.
The API work [to add status to an application summary has been merged.](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/840)
This PR:
* updates the API type to reflect status
* updated the applicationService to add logic (taken from CAS1/3) to group applications by statys
* adds the `govUkTabs` component to the applications dashboard page
* copy tweaks [based on content design](https://trello.com/c/5p2Qf1G2/427-multiple-applications-start-new-application) (note that having copy in the tabs when no applications are there is a bit of complexity that I've said we will shelve for now)
=> Show in progress applications for user

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/applyPage.ts, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/pages/apply/disabilityPage.ts, integration_tests/pages/apply/taskListPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_disability_page.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_equality_questions_page.cy.ts, integration_tests/tests/apply/area_and_funding/funding_information/complete_area_and_funding_section.cy.ts, integration_tests/tests/apply/before_you_apply/confirm_eligibility/confirm_eligibility_task.cy.ts, integration_tests/tests/apply/find_by_crn.cy.ts, integration_tests/tests/apply/view_task_list.cy.ts, server/@types/ui/index.d.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/form-pages/apply/before-you-start/confirm-eligibility/confirmEligibility.test.ts, server/form-pages/apply/before-you-start/confirm-eligibility/confirmEligibility.ts, server/form-pages/apply/before-you-start/confirm-eligibility/index.ts, server/form-pages/apply/before-you-start/index.ts, server/form-pages/apply/index.ts, server/utils/applications/utils.ts, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
In this PR we insert a task into the the applicant journey, in between "Find by CRN" and seeing the task list for the first time:
```
section: Before you start
task: Check eligibility
page: Check eligibility
```
=> [315] Confirm eligibility before you start

.circleci/config.yml
This updates the docker image used in CI to have the same version of playwright that we are using the E2E repo itself, updated in: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/commit/8f265f26f3179ee832249aab83b9bee55db9955c
=> Update playwright version to 1.36.2

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/sexAndGenderPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_sex_gender_page.cy.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/index.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexAndGender.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexAndGender.ts, server/i18n/en/errors.json, server/views/applications/pages/equality-and-diversity-monitoring/sex-and-gender.njk
Adding the 'Sex and gender identity' page to the end of the Equality and Diversity task
E2E PR is here https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/14
=> Add 'Sex and gender identity' page to Equality and Diversity

assets/scss/application.scss, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/pages/apply/ineligiblePage.ts, integration_tests/tests/apply/before_you_apply/confirm_eligibility/confirm_eligibility_task.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts, server/views/applications/ineligible.njk, server/views/partials/layout.njk
[Trello 439](https://trello.com/c/IbeldbIT/439-eligibility-not-eligible-path)
User stories:
- Abandon ineligible application and start new one
- Change eligibility answer: from NO to YES
- Confirm that the person is NOT eligible for CAS-2
If an application has been marked as ineligible, a new "ineligible" view is now rendered. This view provides:
1. confirmation that the application is marked as ineligible
2. a link to change the eligibility answer
3. a link to start a new application
At present ineligible applications will remain in the "dashboard" list of applications but it won't be possible to do anything to them (via the task list) without changing the eligibility answer.
In the future we might choose to set the `applications.is_inapplicable` property in the db. This might be used to …
=> 439 Show dead-end if person marked as ineligible

doc/task_list_system.md, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/sexualOrientationPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_sexual_orientation_page.cy.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/index.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexAndGender.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexAndGender.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexualOrientation.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/sexualOrientation.ts, server/i18n/en/errors.json, server/views/applications/pages/equality-and-diversity-monitoring/sexual-orientation.njk
This adds the sexual orientation page to the E&D task, following disability.
I've also added some bare bones instructions to follow when adding a page - I think we can update them as we go, but I found them helpful to follow so adding for future use!
=> Add Sexual orientation page to Equality and Diversity task

integration_tests/pages/apply/risks-and-needs/healthNeedsGuidancePage.ts, integration_tests/pages/apply/taskListPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/health_needs_guidance_page.cy.ts, server/form-pages/apply/index.ts, server/form-pages/apply/risks-and-needs/health-needs/guidance.test.ts, server/form-pages/apply/risks-and-needs/health-needs/guidance.ts, server/form-pages/apply/risks-and-needs/health-needs/index.ts, server/form-pages/apply/risks-and-needs/index.ts, server/views/applications/pages/health-needs/guidance.njk
See [Trello 328](https://trello.com/c/rmEOYpyy/328-health-needs-guidance-page)
The first task to be implemented in the "Risks and needs" section is 'Health needs'. The first page of this task is a guidance page which doesn't ask any questions but will (in a later PR) offer some copy-able "Get in touch" content for use in email queries to other teams.
```
Section: Risks and needs
Task: Add health needs
Pages:  - Guidance
- [Substance misuse]
- [Physical health]
- [...]
```
Without the copy-able "Get in touch" section and email templates
=> Add 'Health needs' task within new 'Risks and needs' section

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/about_the_person/equality_and_diversity/index.ts, integration_tests/pages/apply/about_the_person/equality_and_diversity/religionPage.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_asian_background.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_black_background.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_ethnic_group_page.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_mixed_background.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_other_background.cy.ts, integration_tests/tests/apply/about_the_person/equality_and_diversity/complete_religion.cy.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/asianBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/asianBackground.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/blackBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/blackBackground.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/ethnicGroup.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/ethnicGroup.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/index.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/mixedBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/mixedBackground.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/otherBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/otherBackground.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/whiteBackground.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/whiteBackground.ts, server/i18n/en/errors.json, server/views/applications/pages/equality-and-diversity-monitoring/religion.njk
Adds the next page in the E&D task, which is structured like this:
So all of the background pages had to have their `next` logic updated, and there will shortly be a new 'military' page added after this page. 
e2e test is here, but will be failing because missing health section atm https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/19
=> Add religion page to Equality & Diversity 

doc/task_list_system.md, integration_tests/pages/apply/risks-and-needs/substanceMisusePage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/substance_misuse.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/utils/utils.ts, server/views/applications/pages/health-needs/substance-misuse.njk, server/views/applications/pages/layout.njk
This PR implements the first real form page in the "Health needs" task: "Substance misuse". (The initial page is a guidance page, and is not included in the left hand navigation).
See [Trello 330](https://trello.com/c/Qg994Nnx/330-health-subsection-substance-misuse)
=> (330) Health task: substance misuse page

integration_tests/pages/apply/risks-and-needs/mentalHealthPage.ts, integration_tests/pages/apply/risks-and-needs/utils.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts, server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts, server/views/applications/pages/health-needs/mental-health.njk, server/views/components/formFields/form-page-text-area/macro.njk
Tweaks to the mental health page
See individual commits:
1) adds a mechanism to add the "(optional)" flag to a text area's label
2) tweak to an error message
=> "Health needs" task: mental health page

integration_tests/mockApis/applications.ts, integration_tests/pages/apply/applicationSubmittedPage.ts, integration_tests/pages/apply/taskListPage.ts, integration_tests/tests/apply/submit.cy.ts, server/@types/shared/index.d.ts, server/@types/shared/models/SubmitCas2Application.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/paths/api.ts, server/paths/apply.ts, server/routes/apply.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/utils/applications/checkResponsesForPagesInTask.test.ts, server/utils/applications/checkResponsesForPagesInTask.ts, server/utils/applications/getApplicationData.test.ts, server/utils/applications/getApplicationData.ts, server/utils/applications/getResponses.test.ts, server/utils/applications/getResponses.ts, server/utils/applications/utils.ts, server/views/applications/confirm.njk, server/views/applications/taskList.njk
API PR here: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/895 
We would like users to be able to mark applications as submitted - this is a first pass at the very minimal functionality to allow users to do this. Does not include validating the application is complete, error handling or correct design for the confirmation page.
=> Mark application as submitted

helm_deploy/hmpps-community-accommodation-tier-2-ui/values.yaml, helm_deploy/values-dev.yaml, server/config.ts, server/services/auditService.test.ts, server/services/auditService.ts
**Background here:** https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/4413030459/Migrate+to+using+IRSA 
**Slack thread:** https://mojdt.slack.com/archives/C03K0HB0LBE/p1692367119011029?thread_ts=1691154904.648879&cid=C03K0HB0LBE
We need to switch over to using IRSA by 4th September to access AWS
services - in the case of CAS UI's this just means SQS.[1]
If I understand correctly, IRSA effectively means our kubernetes service account 
is given an IAM role which it can then use to authenticate, rather than passing in 
access keys/secrets. The service account name has been added to the cloud platform 
repo already (see below).
This PR removes the credentials we were previously using to access
SQS - from now on the kubernetes service account that this pod runs in
should have an IAM role …
=> Switch to IRSA for AWS authentication

assets/scss/application.scss, assets/scss/components/_copy-text.scss, integration_tests/index.d.ts, integration_tests/pages/apply/risks-and-needs/healthNeedsGuidancePage.ts, integration_tests/pages/page.ts, integration_tests/support/commands.ts, integration_tests/tests/apply/risks_and_needs/health-needs/health_needs_guidance_page.cy.ts, integration_tests/tests/apply/risks_and_needs/health-needs/substance_misuse.cy.ts, server/views/applications/pages/health-needs/guidance.njk, server/views/partials/email-templates/drug-alcohol-questions.njk, server/views/partials/email-templates/health-questions.njk, server/views/partials/email-templates/introduce-yourself.njk, server/views/partials/layout.njk
This PR allows users to copy email templates from the health needs guidance page.
The functionality has been implemented via an extra script in the guidance template, and tested in our integration test suite.
=> Health needs guidance page - getting in touch section

.github/shared/setup/action.yml, package-lock.json, server/form-pages/utils/index.test.ts
This PR contains all the [changes from this renovate PR](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/156), plus we've also had to replace `resetAllMocks` in the form page utils because it was now failing, `restoreAllMocks` seems like the more appropriate function to use.
=> Update all non major dependencies

integration_tests/fixtures/applicationData.json, integration_tests/mockApis/person.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/risk_to_self_guidance_page.cy.ts, server/@types/shared/index.d.ts, server/@types/shared/models/OASysRiskToSelf.ts, server/@types/ui/index.d.ts, server/data/personClient.test.ts, server/data/personClient.ts, server/form-pages/apply/risks-and-needs/risk-to-self/index.ts, server/form-pages/apply/risks-and-needs/risk-to-self/riskToSelfGuidance.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/riskToSelfGuidance.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.ts, server/paths/api.ts, server/services/personService.test.ts, server/services/personService.ts, server/testutils/factories/index.ts, server/testutils/factories/oasysRiskToSelf.ts, server/views/applications/pages/risk-to-self/guidance.njk, server/views/applications/pages/risk-to-self/vulnerability.njk
We would like to check if there is OASys information for an applicant on the Risk to Self section.
If there is data, when the user clicks 'save and continue' we populate the relevant answers in the rest of the task.
[We previously used an existing function ](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/173)on the CAS API which gets several sections from the report, and does not include one required part of the Risk to Self section (historical risk of self-harm). 
This PR:
* Uses work from this API PR https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/920 to retrieve only the relevant section of OASys
* adds a skeleton 'Vulnerability' page so that we can see answers populating.
=> Refactor Risk to Self OASys transformation 

integration_tests/pages/apply/risks-and-needs/risk-to-self/acctPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/additionalInformationPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/currentRiskPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/historicalRiskPage.ts, integration_tests/pages/apply/risks-and-needs/risk-to-self/vulnerabilityPage.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/acct.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/additional_information.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/current_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/historical_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/risk_to_self_guidance_page.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/vulnerability.cy.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/index.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.ts, server/views/applications/pages/risk-to-self/_risk-to-self-screen.njk, server/views/applications/pages/risk-to-self/acct.njk, server/views/applications/pages/risk-to-self/additional-information.njk, server/views/applications/pages/risk-to-self/current-risk.njk, server/views/applications/pages/risk-to-self/historical-risk.njk, server/views/applications/pages/risk-to-self/vulnerability.njk
This can be merged after the work to refactor the guidance page https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/176 
We would like to have a bare bones 'scaffolding' for the Risk to Self page, so that we can work on pages in parallel.
This PR adds basic pages (some with text areas so we can see data autopopulating) and basic tests
etc.
=> 470 Risk to Self skeleton

.github/PULL_REQUEST_TEMPLATE.md
A PR to add a default template for our PRs. 
* I wanted to make sure that we don't forget to add `auditEvent`s when we add a new route - let me know if any more docs are required for that.
* Copied mostly from CAS1 but with some changes for us because we don't have preprod/prod environment.
=> add intial PR template

server/config.ts, server/form-pages/apply/risks-and-needs/risk-to-self/riskToSelfGuidance.ts, server/middleware/setUpWebSecurity.ts, server/utils/nunjucksSetup.ts, server/views/partials/layout.njk
setup Google Tag Manager
We would like to use GTM as an analytics tool. This setup adds the
script provided by GTM to start collecting data, with added
configuration for our content security policy:
* we've added the id to our secrets in dev environment
* we've added `www.googletagmanager.com` to our `scriptSrcElem` helmet
policy to allow the script to be executed.[2]
With help from step-by-step guide from the 'Create and Vary a License'
docs here:
https://dsdmoj.atlassian.net/wiki/spaces/CVL/pages/3765338186/Analytics+Setup
setUpWebSecurity.ts though ours have diverged to use the Google Tag
Manager specific scripts.
[2] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-elem
=> setup Google Tag Manager

.circleci/config.yml
Following the lead of the 'Create and vary a licence' team (https://github.com/ministryofjustice/create-and-vary-a-licence/pull/644/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R43) and CAS1, we should temporarily pin the version of NPM we use as NPM 10 isn't compatible with the current version of Node and NPM are yet to update their CHANGELOG to acknowledge version 10 or communicate about its release. If we don't do this we are unable to run our CI pipelines.
confirm:
[Find the …
=> Pin npm version to 9.8.1

assets/scss/application.scss, assets/scss/pages/_oasys-import.scss, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/applyPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/current_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/historical_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/vulnerability.cy.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/riskToSelfGuidance.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/riskToSelfGuidance.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.ts, server/form-pages/utils/index.test.ts, server/form-pages/utils/index.ts, server/views/applications/pages/risk-to-self/current-risk.njk, server/views/applications/pages/risk-to-self/historical-risk.njk, server/views/applications/pages/risk-to-self/vulnerability.njk, server/views/partials/dateOfOasysImport.njk
This PR renders the date that risk to self records were imported into the application from OASys, if records have been imported.
Also temporarily pins the NPM version to unblock our CI pipelines.
confirm:
=> 503 risk to self oasys import date on pages

helm_deploy/values-dev.yaml
This adds the google tag manager ID as a secret for the kubernetes pod to read. The secret has already been added via kubectl. When we have a preprod/prod environment we can add to those values, but initially only needed in dev.
=> add `TAG_MANAGER_ID` secret

server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.test.ts, server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.ts
See [Trello 375](https://trello.com/c/SmsCqlYJ/375-health-subsection-learning-difficulties-and-neurodiversity)
This PR tweaks the text of 2 of the validation error messages shown when follow-on questions are not answered.
=> Tweak 2 validation error messages on Health: Learning difficulties page

server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.test.ts, server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.ts
This PR tweaks the 3 validation error messages where follow-on questions haven't been answered. See [Trello 373](https://trello.com/c/6V6oEPu8/373-health-subsection-communication-and-language-needs)
=> Tweak validation error messages on 'Health: communication needs' page

server/middleware/setUpWebSecurity.ts
This allows any calls to `google-analytics.com` to go through, (as well as our own calls and anything using the `cspNonce`) so that Tag Manager can feed through to GA.
=> add Google analytics to our Content Security Policy

integration_tests/fixtures/applicationData.json, integration_tests/mockApis/person.ts, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/oasysImportPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, server/@types/ui/index.d.ts, server/data/personClient.test.ts, server/data/personClient.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/paths/api.ts, server/services/personService.test.ts, server/services/personService.ts, server/testutils/factories/index.ts, server/testutils/factories/oasysRosh.ts, server/testutils/factories/oasysSections.ts, server/views/applications/pages/risk-of-serious-harm/oasys-import.njk
These changes allow users to import risk of serious harm (RoSH) data from OASys if it exists, or else to continue to manual entry if not. The changes generally follow the lead of the risk to self OASys import page, although the logic for routing users on to subsequent pages is slightly more elaborate. If data has already been imported from OASys, the user should skip the OASys import page but be sent to the RoSH summary page. If data has been inputted but manually, the user should be sent straight to the risk to others page.
Comments on casing particularly welcome :)
confirm:
Once …
=> Allow import of RoSH data from OASys

integration_tests/pages/apply/risks-and-needs/risk-to-self/acctPage.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.ts, server/views/applications/pages/risk-to-self/acct.njk
Changes title of page to match prototype
=> rename title of ACCT page to match design

integration_tests/fixtures/applicationData.json, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.ts
https://trello.com/c/K4wTSYL3/462-risk-to-self-additional-information
This error case was not handled previously.
confirm:
=> Add error handling for no additional information in 'Risk to Self'

integration_tests/mockApis/applications.ts, server/paths/api.ts, server/testutils/jest.setup.ts
[Trello 517](https://trello.com/c/dtLdFRF6/517-implement-cas2-api-namespace)
**NB: this must be merged at the same time as the corresponding change on the API: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/965**
This PR adjusts the UI to use the newly namespaced "applications" endpoints at the CAS API:
confirm:
Once this and the [API side](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/965) are merged we should revert commit https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/commit/619f62e902f105694b3ad383b2dc2 …
=> 517 switch applications to cas2 api namespace

assets/scss/application.scss, assets/scss/components/_rosh-widget.scss, integration_tests/fixtures/applicationData.json, integration_tests/mockApis/person.ts, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/roshSummaryPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/rosh_summary.cy.ts, server/@types/ui/index.d.ts, server/data/personClient.test.ts, server/data/personClient.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/paths/api.ts, server/services/personService.test.ts, server/services/personService.ts, server/testutils/factories/index.ts, server/testutils/factories/risks.ts, server/views/applications/pages/risk-of-serious-harm/summary.njk, server/views/components/roshWidget/macro.njk, server/views/components/roshWidget/template.njk
Updates the RoSH summary page to render a RoSH summary card, based on data that is retrieved from the RoSH OASys import page.
NB following the prototype, I have allowed users to add additional comments to an 'unknown RoSH' summary, although this feels a bit strange to me.
confirm:
fix it as …
=> Add rosh risk summary

server/services/taskListService.test.ts, server/services/taskListService.ts
https://trello.com/c/uKElr23W/531-tech-task-allow-users-to-start-tasks-out-of-order
Our users would like to be able to dip in and out of the form tasks in any order. 
This commit removes the logic that assigns a `cannot_start` status to tasks. We are keeping the `cannot_start` status and logic in the `taskListUtils` because we will in the future be introducing some rules, e.g. the first task should be completed before the rest.
confirm: …
=> allow tasks to be completed in any order

integration_tests/fixtures/applicationData.json, integration_tests/mockApis/applications.ts, integration_tests/pages/apply/applyPage.ts, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/roshSummaryPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/rosh_summary.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/current_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/historical_risk.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/oasys_import_page.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/vulnerability.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-to-self/historicalRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/vulnerability.ts, server/form-pages/utils/index.test.ts, server/form-pages/utils/index.ts, server/views/applications/pages/risk-of-serious-harm/summary.njk
I noticed when filling in the Risk To Self task that the OASyS import date was disappearing from questions that I knew should have them, for example...
date is present when I first see question...
after saving the question and returning, date is gone...
This PR has two parts:
This issue was happening because the import date was saved against each auto-populated page in
a task as a field `oasysImportDate`:
```
task-name: {
page-name: {
oasysData: 'some imported data'
oasysImportDate: '2023-09-19'
}
}
```
However, when a user would then press 'save and continue' to submit
their answer, the field was not included in the body of
the form and so overwritten when the data was updated.
```
task-name: {
page-name: {
oasysData: 'some updated imported data'
confirmation: 'confirmed'
}
}
```
I think …
=> Risk to self errors

integration_tests/mockApis/person.ts, script/generate-types, server/@types/ui/index.d.ts, server/data/personClient.test.ts, server/data/personClient.ts, server/paths/api.ts, server/services/personService.test.ts, server/services/personService.ts, server/testutils/jest.setup.ts
This PR should be merged at the same time as the API [PR 991: use CAS2 with NOMIS credentials](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/991)
It includes changes to make the UI compatible with i) newly namespaced endpoints and ii) the separate new-style 'built' CAS2 OpenAPI spec:
- puts API calls to the 'people' endpoints into the new `/cas2/` namespace
- removes unused and no longer supported `PersonService.getOasysSections()` function
- changes the path to the CAS2 OpenAPI spec in the Typescript type generator
- changes the path to the CAS2 OpenAPI spec for PACT testing and reformats the specification to work around limitation in the PACT testing library
ready to be released at any …
=> 559: switch UI paths to use CAS2 people endpoints

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/roshSummaryPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/rosh_summary.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts
Alex picked up in QA that the risk widget in the RoSH task displays correctly on first visit, but then becomes the 'unknown risk' version on second visits.
The RoSH risk ratings are retrieved from the API and saved to our application data by the `oasysImport` page. This data is then retrieved from the application data used to populate the 'risk widget' by the Summary page.
The risk ratings were previously stored under the key for the Summary page, `summary`. When the user first lands on the Summary page we are able to see the widget, but when the user presses 'continue' the form page takes that `summary` key and uses it to overwrite the data that's there with it's own form data (see `save` function in the `applicationService`). Thus deleting the risk widget data.
This commit proposes a …
=> Fix: RoSH risk summary not displaying on second viewing

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.ts, server/views/applications/pages/risk-of-serious-harm/behaviour-notes-data.njk, server/views/applications/pages/risk-of-serious-harm/behaviour-notes.njk, server/views/applications/pages/risk-to-self/acct-data.njk
This should address all the issues found here https://trello.com/c/c1U9s1L1/414-rosh-behaviour-notes-was-prison-notes#comment-651ebd2e22daf820ce66bb71 
* Error message - the error summary should be at the top of the page (before the title) - _also changed this for ACCT notes_
* Missing personalisation from the title “Add a behaviour note Terry Midhurst”
* Missing hint text for “Describe the behaviour” 
* Missing “Cancel” link
=> Fixes/tweaks for Behaviour Notes

server/views/applications/pages/risk-of-serious-harm/risk-management-arrangements.njk
Missing an `'s` - this should work if the copy is either 'the person' or the actual person's name
=> fix grammar on person's name

.circleci/config.yml, helm_deploy/values-preprod.yml
We would like to begin user testing some features of the service in a production-like environment. 
Cloud Platform PR merged here  https://github.com/ministryofjustice/cloud-platform-environments/pull/17070 
Bootstrap PR here https://github.com/ministryofjustice/dps-project-bootstrap/pull/518 
HMPPS Auth setup here https://dsdmoj.atlassian.net/browse/HAAR-1978 
This PR:
* adds the values needed to deploy to the `preprod` environment.
* adds the CircleCI workflow to manually deploy to preprod. Unlike test and dev, I'm going to require that the e2e tests are passing because we need to have confidence in our pipeline, but open to changing that if we think it's going to hold up things.
ready to be released at any …
=> Add preprod values for deployment

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotes.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/behaviourNotes.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/behaviourNotesData.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/acct.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/acctData.ts, server/form-pages/utils/questions.ts, server/utils/checkYourAnswersUtils.ts
We would like to decouple as much as possible the Check Your Answers utility function from specific page keys.
For pages that we will not render on CYA:
* we do not need to return anything from the `getQuestions` util
* we will return an empty object from the `response` function for the page. This is the purpose of that function, to allow for custom responses rather than specifying in the CYA utilities.
This change removes the need for a hand-rolled list. We still need to include the `summary` pages currently, but will create a future ticket to render that data in it's own way. 
Should be no changes to rendering of Check Your Answers …
=> Add custom `response` to data pages

integration_tests/mockApis/applications.ts, integration_tests/tests/apply/submit.cy.ts, script/generate-types, server/@types/shared/index.d.ts, server/@types/shared/models/Cas2SubmittedApplication.ts, server/@types/shared/models/Cas2SubmittedApplicationSummary.ts, server/@types/shared/models/SubmitCas2Application.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/paths/api.ts, server/testutils/jest.setup.ts, server/utils/applications/getApplicationData.test.ts, server/utils/applications/getApplicationData.ts
**This PR should be merged at the same time as the accompanying change at the CAS API https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1085**
There is no change in behaviour from the point of view of users or end-to-end tests.
=> Move application submission to new /cas2/submissions endpoint

assets/scss/application.scss, assets/scss/components/_tag.scss, server/form-pages/apply/offence-and-licence-information/offending-history/offenceHistory.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/offenceHistory.ts
https://trello.com/c/kBofxIPG/418-epic-offence-history-add-a-previous-offence
adding a custom brown colour to the tags, as the colours provided by GDS not contrasty enough. Hex codes taken from prototype.
confirm:
=> Correct colour for offence history tags

integration_tests/pages/apply/risks-and-needs/health-needs/substanceMisusePage.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/views/applications/pages/health-needs/substance-misuse.njk
See [Trello 330](https://trello.com/c/Qg994Nnx/330-health-subsection-substance-misuse)
Tweaks to Substance misuse page in Health Needs task.
=> (330) Mk3 Health Needs: Substance misuse - tweaks

server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.test.ts, server/form-pages/apply/risks-and-needs/health-needs/learningDifficulties.ts
See [Trello 375](https://trello.com/c/SmsCqlYJ) - Health section: learning difficulties
=> Tweak validation error msg when detail missing from 'additional needs' question

integration_tests/pages/submissions/submissionPage.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, server/controllers/apply/applicationsController.ts, server/testutils/factories/application.ts, server/views/applications/show.njk
Following on from the Assessor view being merged, this is a cheeky add of the same component to the referrer view.
It should look the same as the screenshots in this PR https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/279 
confirm:
=> Referrer views submitted application

server/controllers/apply/applicationsController.ts
On applications that are not submitted the key will be present but the value will be `null`.
=> Fix check for submitted application

assets/scss/application.scss, assets/scss/components/_checkboxes.scss, server/form-pages/apply/area-and-funding/funding-information/alternativeID.test.ts, server/form-pages/apply/area-and-funding/funding-information/alternativeID.ts, server/views/applications/pages/funding-information/alternative-identification.njk
When the divider was passed as the first element to the checkbox component, the `for` id given to the next checkbox had a `-2` at the end. This meant that if there was an error summary it was not able to link to the first checkbox.
I couldn't see a way to override the index-based attributes given to the checkbox items, so this is a bit of a hacky way of adding a divider without adding it to the items.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpp …
=> Add custom CSS to funding checkbox

server/form-pages/apply/area-and-funding/funding-information/identification.test.ts, server/form-pages/apply/area-and-funding/funding-information/identification.ts
Add hint text from prototype to driver's licence and wage slip checkbox. Because of the way we iterate through the checkbox values I've hardcoded them in the `items` function. Open to other suggestions!
confirm:
=> Add hint text for identification checkboxes

integration_tests/pages/apply/risks-and-needs/health-needs/substanceMisusePage.ts, server/views/applications/pages/health-needs/substance-misuse.njk
Fix missing "label" for follow-up substitute medication question on "Substance misuse" page within **Health Needs**
=> (330) Health needs: fix missing "Substitute medication" follow-up question on substance misuse page

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/area_and_funding/area_information/FirstPreferredAreaPage.ts, integration_tests/tests/apply/area_and_funding/area_information/first_preferred_area.cy.ts, server/form-pages/apply/area-and-funding/area-information/firstPreferredArea.test.ts, server/form-pages/apply/area-and-funding/area-information/firstPreferredArea.ts, server/form-pages/apply/area-and-funding/area-information/index.ts, server/form-pages/apply/area-and-funding/index.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/area-information/_area-information-screen.njk, server/views/applications/pages/area-information/_preferred-area.njk, server/views/applications/pages/area-information/first-preferred-area.njk
* Adds the `AreaInformation` task which sits under "Area & funding"
* Adds a new page to the apply journey `FirstPreferredArea`
confirm:
=> (577) Introduce first preferred area page

integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/tests/assess/view_application_overview.cy.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts
The name has been added on the API side, so now
we can display on the timeline and provide a more readable design
confirm:
=> display external user name on application timeline

integration_tests/mockApis/applications.ts, integration_tests/pages/apply/confirmApplicantPage.ts, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/tests/apply/before_you_apply/confirm_eligibility/confirm_eligibility_task.cy.ts, integration_tests/tests/apply/confirm_applicant_details.cy.ts, integration_tests/tests/apply/find_by_prison_number.cy.ts, server/@types/shared/models/FullPerson.ts, server/@types/ui/index.d.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/peopleController.test.ts, server/controllers/peopleController.ts, server/data/personClient.ts, server/routes/apply.ts, server/routes/index.ts, server/services/personService.ts, server/testutils/factories/person.ts, server/utils/assessUtils.test.ts, server/utils/assessUtils.ts, server/utils/nunjucksSetup.ts, server/utils/personUtils.test.ts, server/utils/personUtils.ts, server/utils/utils.test.ts, server/utils/utils.ts, server/views/people/confirm-applicant-details.njk, server/views/people/partials/personDetails.njk
https://trello.com/c/QxtY2FOY/314-confirm-applicant 
Confirm applicant details, after searching for them using a prison number
needs this API PR to merge https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1189 
This has involved moving the `create` application function back to the applications controller, rather than creating the application directly in the people controller. 
* I've put in some error handling on the applications controller `create` function:
```
try {
const application = await this.applicationService.createApplication(req.user.token, crn)
res.redirect(paths.applications.show({ id: application.id }))
} catch (error) {
req.flash('errors', {
prisonNumber: {
text: 'There was an error creating the application, please try again',
attributes: { …
```
=> Confirm applicant details

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/before_you_start/confirm_consent/confirmConsentPage.ts, integration_tests/pages/apply/before_you_start/confirm_consent/consentRefusedPage.ts, integration_tests/pages/apply/confirmEligibilityPage.ts, integration_tests/tests/apply/before_you_apply/confirm-consent/confirm_consent.cy.ts, integration_tests/tests/apply/before_you_apply/confirm_eligibility/confirm_eligibility_task.cy.ts, integration_tests/tests/apply/view_task_list.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/form-pages/apply/before-you-start/confirm-consent/confirmConsent.test.ts, server/form-pages/apply/before-you-start/confirm-consent/confirmConsent.ts, server/form-pages/apply/before-you-start/confirm-consent/index.ts, server/form-pages/apply/before-you-start/index.ts, server/form-pages/utils/questions.ts, server/utils/applications/utils.ts, server/views/applications/consent-refused.njk, server/views/applications/pages/confirm-consent/confirm-consent.njk, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
[Trello ticket](https://trello.com/c/xBJboq8O/181-verbal-consent-form)
This PR adds the 'Confirm consent' task to the 'Before you start' section, and ensures that users will be redirected from 'Confirm eligibility' to 'Confirm consent' without having to navigate via the task list. The code that does this, in `applicationsController`, is a bit unwieldy, so let me know if you can see any good opportunities to refactor it.
confirm: …
=> Verbal consent form

server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
Another go at adding criterion on living independently to the eligibility checklist. This has come from an agreed policy change. 
[Trello ticket 703](https://trello.com/c/X35FaugR/703-content-tweak-eligibility-add-living-independently-criterion
)
confirm:
=> Add living independently criterion to eligibility checklist

server/views/applications/pages/personal-information/working-mobile-phone.njk
We want to be able to e2e test this page. As there are two identical
radio inputs with the "Yes" label, we want a way to differentiate
between the two.
We do this by using the page heading as the fieldset `legend`, to
associate the heading with the form.
confirm:
=> Use fieldset for working mobile phone page header

integration_tests/fixtures/applicationData.json, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/about_the_person/personal_information/immigrationStatusPage.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.test.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/personal-information/immigration-status.njk
We want referrers to easily choose an applicant's immigration status by
providing pre-determined options.
confirm:
=> (456) Provide options for immigration status page 

integration_tests/pages/apply/confirmApplicantPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, integration_tests/tests/apply/confirm_applicant_details.cy.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/utils/checkYourAnswersUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/applications/show.njk, server/views/assess/applications/show.njk, server/views/partials/applicantDetails.njk
This is a reduced version of this PR https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/360 
With just the code to render the person details on CYA and submitted applications. 
Note:
When we first confirm the applicant details on the API we use the `nomsNumber` to make a call to `probation-offender-search` and show the person's details
Subsequent calls to get the Person are via the community api, which might not necessarily have the same or all the data, hence some missing fields (pnc and nationality) locally for Aadland. We'll have to do some API work to prevent this.
confirm:
`auditEvent`? (see …
=> Render applicant details on application

server/views/applications/pages/current-offences/current-offence-data.njk, server/views/applications/pages/offending-history/offence-history-data.njk
Change the example of the types of offences the user needs to record separate from sexual harassment to drug-related as sexual harassment offences would make someone ineligible for Home Detention Curfew (HDC) licence (and the service at present).
[Trello ticket 728](https://trello.com/c/ZI6aEpVv/728-content-change-the-prompt-for-the-add-one-offence-to-one-that-isnt-sexual-harassment-to-an-offence-that-is-eligible-for-hdc)
confirm: …
=> Change offence example in guidance to one eligible for HDC licence

server/views/applications/pages/health-needs/physical-health.njk
Another go at adding hint text to specify what living independently means to the related question in physical health. 
[Trello ticket 702](https://trello.com/c/rbGwzD3y/702-content-tweak-physical-health-add-hint-text-to-can-they-live-independently)
confirm:
=> Add hint text to independent living question in physical health

server/views/applications/pages/health-needs/physical-health.njk
Add hint text to specify what physical health needs the user should consider when answering whether the applicant has physical health needs.
[Trello ticket 711](https://trello.com/c/oOHv04ez/711-content-tweak-physical-health-add-hint-text-to-do-they-have-physical-health-needs)
confirm:
fix it …
=> Add hint text to physical health needs

integration_tests/fixtures/applicationData.json, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.ts, server/views/applications/pages/check-your-answers/check-your-answers.njk
In another PR the checkbox was removed from the task list page[1].
This piece of work adds it to the check your answers page and requires the referrer to check the box before marking as complete.
[1]
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/378
confirm: …
=> (685) Add confirmation checkbox to check your answers page

server/app.ts, server/errorHandler.test.ts, server/errorHandler.ts
We want the error handling as close as possible to prod in our test environment, this ensures that error messages and stack traces are shared in environments that are NOT test or production.
https://trello.com/c/nsMHl851/667-tech-task-turn-on-error-handling-in-preprod-and-test
=> turn on error handling in environments that are not dev/local

server/@types/express/index.d.ts, server/controllers/index.ts, server/controllers/report/reportsController.test.ts, server/controllers/report/reportsController.ts, server/data/index.ts, server/data/reportClient.test.ts, server/data/reportClient.ts, server/data/restClient.ts, server/paths/api.ts, server/paths/report.ts, server/routes/index.ts, server/routes/report.ts, server/services/index.ts, server/services/reportService.test.ts, server/services/reportService.ts, server/testutils/jest.setup.ts, server/utils/nunjucksSetup.ts, server/views/reports/new.njk
[Trello 719](https://trello.com/c/0HPZIytR/719-placeholder-mi-view-for-ithc)
This PR provides an initial user-interface to download a "report" of management information. The download is in `.xlsx` format and is only available to users with the `CAS2_MI` role. It's exposed via the `/reports` url.
The report itself is an example placeholder report `cas2-example-report.xlsx`.
The purpose of this work is to implement the framework for providing downloadable spreadsheets to users.
Note that the authorisation control is implemented at the API. i.e. a user without the required role can navigate to `/reports` and attempt to "Download report". They will receive a 403 Forbidden response. In the future we *may* implement authorisation controls in the UI to prevent the `/reports` url from being …
=> MI user downloads "report" spreadsheet of metrics

server/form-pages/utils/questions.ts, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
1. Add outstanding charge committed during current sentence as a new criterion on the eligibility checklist
2. Tweak outstanding charge question when adding a current offence to specify the type of outstanding charge
[Trello ticket 727](https://trello.com/c/vlC5mMkK/727-content-outstanding-charges-and-hdc-licence-eligibility)
confirm:
Should a release fail at any step, you …
=> Add outstanding charge eligibility criterion and tweak outstanding charge question

server/views/applications/pages/current-offences/current-offence-data.njk
Add hint text to conditional outstanding charges detail question to specify which outstanding charges the user should provide.
[Trello ticket 727](https://trello.com/c/vlC5mMkK/727-content-outstanding-charges-and-hdc-licence-eligibility)
confirm:
=> Add hint text to conditional outstanding charges detail question

integration_tests/pages/dashboardPage.ts, server/views/partials/header.njk
[Trello ticket](https://trello.com/c/eSRTtszd/492-phase-banner-feedback)
confirm:
=> Add phase banner

server/views/applications/new.njk, server/views/applications/pages/current-offences/current-offence-data.njk, server/views/applications/pages/layout.njk, server/views/applications/pages/offending-history/offence-history-data.njk, server/views/applications/pages/risk-of-serious-harm/behaviour-notes-data.njk, server/views/applications/pages/risk-to-self/acct-data.njk, server/views/assess/statusUpdate/new.njk
[Trello ticket ](https://trello.com/c/WTc3jGN0/731-disable-autocomplete-on-all-form-fields)
Sets auutocomplete to "off" on all relevant forms, as well as the status update form, where there is currently no text input but there may plausibly be in the future.
confirm:
fix it as soon as …
=> Disable autocomplete on all form fields

server/views/applications/pages/offending-history/offence-history.njk
Remove 'serious' from offence history guidance
Related to [Trello ticket 729](https://trello.com/c/P1e8i40k/729-content-define-serious-and-non-serious-in-offence-sections)
confirm:
=> Remove 'serious' from offence history guidance

server/utils/userUtils.ts
Tweak homepage tile content to:
- change ‘New referral’ tile to describe action the user is taking with a verb (like we have with ‘View referrals')
- edit description in the new referral tile to specify that new referrals are for HDC applicants only
[Trello ticket 724](https://trello.com/c/ms8FWLuQ/724-check-homepage-tile-content)
confirm:
Should a release fail at any …
=> Tweak homepage tile content

server/views/applications/pages/confirm-consent/confirm-consent.njk
Change to consent page to:
- add bullet point to reference privacy notice for users to show applicants (link to privacy notice page to be added in a following PR)
- tweak wording in existing bullet point from "information" to "personal data" for consistency with new privacy notice bullet
[Trello ticket 452](https://trello.com/c/qzRGzf4n/452-content-privacy-notice)
confirm: …
=> Add privacy notice bullet point to consent page

.circleci/config.yml
we would like to temporarily remove the requirement for e2e tests to be
passing for a product review - we are aware the tests are failing
because a new task (Check information) has been added to the task list.
=> Remove e2e test dependency

helm_deploy/values-preprod.yaml
It has been agreed that our production environment will be accessible to the public, protected by HMPPS Auth and 2FA. Our preproduction environment is currently only accesible via approved IPs, but should have parity with production.
This sets the IP `allowlist` to `null` which means that any IP will be allowed to access (as is the case currently with dev and test environments)
=> Allow access to preprod from anywhere

integration_tests/pages/reports/managementInfoDownloadsPage.ts, integration_tests/tests/dashboard.cy.ts, integration_tests/tests/reports/download_management_info.cy.ts, server/@types/shared/models/SubmitCas2Application.ts, server/controllers/report/reportsController.test.ts, server/controllers/report/reportsController.ts, server/data/reportClient.test.ts, server/data/reportClient.ts, server/paths/api.ts, server/paths/report.ts, server/services/reportService.test.ts, server/services/reportService.ts, server/testutils/jest.setup.ts, server/utils/applications/getApplicationData.test.ts, server/utils/applications/getApplicationData.ts, server/utils/applications/managementInfoFromAppData.test.ts, server/utils/applications/managementInfoFromAppData.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts, server/views/reports/new.njk
[Trello 742](https://trello.com/c/GEIpAHHy/742-generate-report-of-applicationsubmitted-events)
A user with the `CAS2_MI` role can now download a spreadsheet of information about submitted applications. 
See 
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1284 and
- https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1294
for information about the download. It features the following columns:
```
- eventId: 63cbe435-768e-43ab-9164-a57784926f91
- applicationId: 6620721f-eba5-4a10-affb-dd3309b04f41
- personCrn: X320741
- personNoms: A1234AI
- referringPrisonCode: LEI
- preferredAreas: Leeds | Bradford
- hdcEligibilityDate: 2023-03-30
- conditionalReleaseDate: 2023-04-29
- submittedOn: 2024-01-03
- submittedBy: POM_USER
```
`auditEvent`? - the …
=> (742) Download "submitted applications" report

server/controllers/dashboardController.test.ts, server/controllers/dashboardController.ts, server/middleware/populateCurrentUser.test.ts, server/middleware/populateCurrentUser.ts, server/middleware/setUpMaintenancePageRedirect.test.ts, server/middleware/setUpMaintenancePageRedirect.ts, server/services/userService.ts
https://trello.com/c/QqHdrhLZ
- The maintenance page can be bypassed by any user with role CAS2_ADMIN. This will allow the team to test the service is performing properly and debug any issues before disabling maintenance mode.
- The extraction of user roles was handled by the `dashboardController` so we went into a rabbit hole to try and bring that behaviour into the `populateCurrentUser` middleware to make it centralised.
- The data should probably be stored in res.session rather than res.session but that felt like one rabbit hole too far for this one
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/912473/2ca85435-3e87-4120-b7be-ea9805d59883
ready to be released at any …
=> (754) Allow users with the CAS2_ADMIN role to bypass maintenance

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/applyPage.ts, integration_tests/pages/apply/risks-and-needs/risk-of-serious-harm/roshSummaryPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/oasys_import.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/rosh_summary.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/oasys_import_page.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/oasysImport.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/currentRisk.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/oasysImport.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/custom-forms/oasysImport.ts, server/form-pages/utils/index.test.ts, server/form-pages/utils/index.ts, server/form-pages/utils/questions.ts, server/testutils/factories/risks.ts, server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts, server/views/applications/pages/risk-of-serious-harm/summary.njk
[Trello ticket ](https://trello.com/c/517sYjty/631-cya-sa-add-oasys-dates)
This PR renders OASys started, completed and imported dates to the user on the check your answers and submitted application pages. It also renders the RoSH summary data on these pages. I have saved this data on the oasys-import pages for RoSH and risk to self, and created custom responses on the RoSH summary and risk to self 'current risk' pages to render this data. This is not ideal and requires the page to handle data unrelated to current risk, but for now it appears the least intrusive solution.
The PR also removes the 'last updated' OASys data across the service, since we have learned that it is based entirely on the date started and date completed data. Rather than extrapolating to a value with questionable …
=> Add OASys dates and RoSH summary data to check your answers

helm_deploy/values-preprod.yaml
We want to test [our new maintenance page](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/413) works in preprod before relying on it in prod. We'll push this, deploy it and then revert it to make sure the containers are restarted with the new environment variable.
confirm:
Should a release fail at any step, you as the author should now …
=> Turn on maintenance mode in preprod to test it

server/config.ts, server/middleware/setUpMaintenancePageRedirect.test.ts, server/middleware/setUpMaintenancePageRedirect.ts
We aren't seeing the maintenance page on preprod desipite the flag being on and nobody being an admin. https://community-accommodation-tier-2-preprod.hmpps.service.justice.gov.uk/
When loading this variable through Helm on preprod (when the value is set to `false`) we get the value coming out of the pod:
```
IN_MAINTENANCE_MODE=true
```
This is on the face of it ok as it’s how we set it locally with .env:
```
IN_MAINTENANCE_MODE=false
```
I think it’s not working because .env loads it as a string but YAML recognises it as a boolean[1].
[1] https://helm.sh/docs/chart_best_practices/values/#make-types-clear
Given we want to use .env locally we continue to check for string for wider compatibility. We could also go the other way and explicitly set it as a string in YAML.
As part of our …
=> IN_MAINTENANCE_MODE will accept true as a string or a boolean

integration_tests/pages/reports/managementInfoDownloadsPage.ts, server/views/reports/new.njk
[Trello 765](https://trello.com/c/GV3HWCzy/765-download-application-status-updates-report)
confirm:
=> 765 download application status updates report

integration_tests/pages/reports/managementInfoDownloadsPage.ts, server/views/reports/new.njk
See [Trello 766](https://trello.com/c/vN0AmVz2/766-download-un-submitted-applications-report)
Adds a link to download from API: `/cas2/reports/unsubmitted-applications`
=> Add a link for MI_USER to download 'Un-submitted applications' report

integration_tests/tests/dashboard.cy.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts
This removes the 'view/create referrals' tiles from the dashboard home page for Admin's. 
Previously we thought that Admin's should be able to make applications, but we are now restricting that to POM's only. Admin's such as contract managers should only be able to view submitted applications.
=> Restrict tiles for CAS2_ADMIN to 'Submitted applications'

integration_tests/pages/apply/applyPage.ts, integration_tests/tests/apply/offence_and_licence_information/current-offences/current_offence_data.cy.ts, integration_tests/tests/apply/offence_and_licence_information/offending-history/offence_history_data.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/behaviour_notes_data.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-to-self/acct_data.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/form-pages/apply/offence-and-licence-information/current-offences/currentOffences.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/currentOffences.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.ts, server/utils/applications/utils.ts, server/views/applications/pages/current-offences/current-offence-data.njk, server/views/applications/pages/offending-history/offence-history-data.njk, server/views/applications/pages/risk-of-serious-harm/behaviour-notes-data.njk, server/views/applications/pages/risk-to-self/acct-data.njk
[Trello ticket](https://trello.com/c/qN2NwjFw/555-add-confirmation-panel-to-the-top-of-the-screen-when-save-and-add-another-has-been-used)
Adds success notification banners for ACCTs, behaviour notes, current and historic offences. These will render when the user selects 'Save and add another', remaining on the same page, so that they understand that their previous entry has been saved.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-acc …
=> Add confirmation panel to the top of the screen when save and add another has been used

integration_tests/pages/reports/managementInfoDownloadsPage.ts, server/views/partials/layout.njk, server/views/reports/new.njk
See [Trello 775](https://trello.com/c/yBEek6bp/775-limit-mi-reports-to-last-12-months)
We use the "warning text" component:
https://design-system.service.gov.uk/components/warning-text/
=> (775) Add a 'warning' notice that MI data is limited to past year.

server/@types/nunjucks/index.d.ts, server/utils/nunjucksSetup.ts
When a global function in a template throws an error, we don’t see the full trace of the error, which makes diagnosing issues really hard.
This makes use of the [undocumented dev argument](mozilla/nunjucks#1430) which allows us to see the cause of the error in our logs and in Sentry.
[Copied from CAS1.](https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/490/commits/8eed08b4e8698b0ad16bc285f731bc8b8f0cd3b2)
confirm: …
=> Allow full error trace in Nunjucks

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/offence_and_licence_information/current-offences/currentOffencesPage.ts, integration_tests/pages/apply/offence_and_licence_information/offending-history/offenceHistoryPage.ts, server/form-pages/apply/offence-and-licence-information/current-offences/currentOffences.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.ts, server/form-pages/apply/offence-and-licence-information/offending-history/offenceHistory.test.ts, server/form-pages/utils/questions.ts
https://trello.com/c/XLkKfuLw/769-remove-the-oasys-code-number-request-on-offences-entries-in-current-offence-and-offence-history-sections
Removes offence codes across the service, after user feedback told us they are confusing.
confirm:
=> Remove offence codes

server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.test.ts, server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.ts, server/form-pages/apply/about-the-person/personal-information/supportWorkerPreference.test.ts, server/form-pages/apply/about-the-person/personal-information/supportWorkerPreference.ts, server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.test.ts, server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.test.ts, server/form-pages/apply/area-and-funding/area-information/exclusionZones.ts, server/form-pages/apply/area-and-funding/area-information/gangAffiliations.test.ts, server/form-pages/apply/area-and-funding/area-information/gangAffiliations.ts, server/form-pages/apply/offence-and-licence-information/hdc-licence-and-cpp-details/nonStandardLicenceConditions.test.ts, server/form-pages/apply/offence-and-licence-information/hdc-licence-and-cpp-details/nonStandardLicenceConditions.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/additionalRiskInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/additionalRiskInformation.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/cellShareInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/cellShareInformation.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskManagementArrangements.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/additionalInformation.ts
We [previously added an `onSave` method to pages](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/388) that would remove stale data whenever the page is updated. In this PR we expand this pattern to other parts of the application.
confirm:
fix it as soon as …
=> (644) Add onSave method to questions

helm_deploy/values-prod.yaml
To enable a testing session today.
I will be watching [for any prod domain events](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz3LMQ6AIAwAwN1XdGPiCYyuDn7AEGjAhLaEgi4%252BXlnc78LQLrReyF2XB%252B6MDSEUGfHYpeDmCcE5MJlqVRuF%252FMkWJ7dFUsJm%252FsXTBuH%252BEQUTvJoX9nLsVl4AAAA%253D/timespan/PT12H) to ensure nobody uses the service to create a referral in the short window we're out of maintenance. We are currently obscured by the fact nobody knows how to find the service. If we find something …
=> Turn off maintenance mode in prod

server/views/static/maintenance.njk
As part of our plan for being offline we proactively point users back to using the old form. This will hopefully avoid support requests and ensure minimal disruption to referrals.
[Conversation and where we find what link to use](https://mojdt.slack.com/archives/C04T6SC31HA/p1705577258492259).
We are planning to hold this pending confirmation that that link is definitely correct before releasing.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-com …
=> Maintenance page steers users to the old referral form

server/views/reports/new.njk
See [Trello 781](https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1360)
We've tweaked this report to provide the submission timestamp rather than just the date.
See https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1360 for change at the API
=> Update 'details' info of 'Submitted applications' MI report

server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.ts
We previously implemented an `onSave` method which we use to remove stale data when the answer to a question changes.
This change addresses a bug where the "other" disability data is not being deleted when the checkbox isn't selected.
confirm:
=> Fix bug where other disability data is not removed

server/utils/checkYourAnswersUtils.ts
Reverts ministryofjustice/hmpps-community-accommodation-tier-2-ui#472
This change allowed for the viewing of the check your answers page without having to have started all of the tasks. We'll keep it in until we guard against viewing the CYA page without having completed the rest of the tasks.
=> Revert "Remove code used to submit incomplete applications"

helm_deploy/values-prod.yaml
Now we are about to release to private beta, we want to enable GTM. Providing a value for the the TAG_MANAGER_ID variable will allow the script in `server/views/partials/layout.njk` to run.
https://dsdmoj.atlassian.net/browse/CAS2-171
confirm:
=> add google tag manager to prod environment

server/views/applications/pages/personal-information/immigration-status.njk
JIRA ticket: https://dsdmoj.atlassian.net/browse/CAS2-141?atlOrigin=eyJpIjoiNDA0ZTUyN2MwZGE1NDQyZjgzMWM3OWViNDRlODRkMzIiLCJwIjoiaiJ9
An accessibility report flagged this page for not having a label
associated with the select field. This commit changes the legend to an
explicit label.
confirm: …
=> Use a label instead of hint for immigration status question

e2e-tests/steps/apply.ts, integration_tests/tests/apply/find_by_prison_number.cy.ts, server/views/applications/before-you-start.njk, server/views/applications/index.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-144
E2E PR: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-e2e/pull/67
This fixes the start an application journey, ensuring that the links direct the user first to the 'Before you start' guidance page and then to the 'Find by prison number' page.
confirm:
Should a release fail at any step, …
=> Tweaks user journey to 'Find by prison number' page

server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/paths/apply.ts, server/routes/apply.ts
JIRA tickets
[Consent](https://dsdmoj.atlassian.net/browse/CAS2-134?atlOrigin=eyJpIjoiNDQ3ODE2NmY4MDY2NGEyZmEyODQ5N2U5YTg2N2Y5MDEiLCJwIjoiaiJ9)
[Eligibility](https://dsdmoj.atlassian.net/browse/CAS2-135?atlOrigin=eyJpIjoiMDU0MGNiMDVmZDNkNDhmMzg1ZWFiOTIyNjViM2ZjNWEiLCJwIjoiaiJ9)
We want to use Google Analytics to get better insights into when the
ineligible & consent refused application page is being shown to referrers.
Previously, these page URLs were the same as viewing a single application
(`applications/{applicationId}`). Now they render with unique paths:
* `applications/{applicationId}/not-eligible`
* `applications/{applicationId}/no-consent-given`
ready to be released at any point. Before merging to …
=> Change URL path for ineligible application page

assets/scss/application.scss, assets/scss/components/_side-nav.scss, integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, integration_tests/tests/apply/view_submitted_application_as_referrer.cy.ts, integration_tests/tests/assess/update_application_status.cy.ts, integration_tests/tests/assess/view_submitted_application.cy.ts, server/@types/ui/index.d.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts, server/utils/nunjucksSetup.ts, server/utils/utils.ts, server/views/applications/pages/check-your-answers/check-your-answers.njk, server/views/applications/show.njk, server/views/assess/applications/show.njk, server/views/components/sideNav/macro.njk, server/views/partials/documentSummaryList.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-68
This PR adds a side navigation component for use on the Check your answers page and submitted application views.
confirm:
=> Add side navigation to CYA and submitted application views

e2e-tests/steps/apply.ts, e2e-tests/steps/assess.ts, e2e-tests/steps/checkAnswersSection.ts, e2e-tests/tests/01_apply.spec.ts, e2e-tests/tests/02_admin.spec.ts
The h1 for a submitted application/CYA view has changed, this corrects expected copy to reflect that.
=> Add hero banner copy to e2e tests

integration_tests/mockApis/submissions.ts, integration_tests/pages/submissions/submissionListPage.ts, integration_tests/tests/assess/view_all_submitted_applications.cy.ts, server/@types/ui/index.d.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/data/restClient.ts, server/data/submittedApplicationClient.test.ts, server/data/submittedApplicationClient.ts, server/services/submittedApplicationService.test.ts, server/services/submittedApplicationService.ts, server/testutils/factories/index.ts, server/testutils/factories/paginatedResponse.ts, server/utils/getPaginationDetails.ts, server/utils/nunjucksSetup.ts, server/utils/pagination.test.ts, server/utils/pagination.ts, server/views/assess/applications/index.njk
This adds pagination to `/assess/applications` which lists all submitted
applications, and can be viewed by assessors (if they know the link) and CAS2 admin's (e.g. Suzie/members of our team)
We are using the existing utility functions from CAS1 and the govuk pagination component.
confirm:
fix …
=> 137 paginate submitted applications

e2e-tests/steps/assess.ts, e2e-tests/tests/03_assess.spec.ts
As the dev environment has seeded data with test
names, the test has to be neutral on the personal
details of the application it picks, and just
check for known elements.
=> fix assessor e2e tests to be person-agnostic

integration_tests/pages/apply/taskListPage.ts, integration_tests/tests/apply/view_task_list.cy.ts, server/services/taskListService.test.ts, server/services/taskListService.ts, server/utils/taskListUtils.ts, server/views/partials/taskListItems.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-170
I currently cannot run E2E tests locally due to issues with Playwright and mobile internet so I would appreciate if the reviewer could check that the tests pass on their machine.
confirm: …
=> Ensure that CYA cannot be started until all prior tasks are complete

e2e-tests/steps/offenceAndLicenceInformationSection.ts, integration_tests/fixtures/applicationDocument.json, integration_tests/pages/apply/offence_and_licence_information/offending-history/anyPreviousConvictionsPage.ts, integration_tests/tests/apply/offence_and_licence_information/offending-history/any_previous_convictions.cy.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.test.ts, server/form-pages/apply/offence-and-licence-information/offending-history/anyPreviousConvictions.ts, server/form-pages/utils/questions.ts, server/testutils/factories/oasysSections.ts
Tweak to previous conviction question page to:
- specify that the question is about unspent convictions
- remove 'this is their first offence' from the 'No' answer, as the applicant may have previous convictions that are not unspent
[Jira ticket 261](https://dsdmoj.atlassian.net/browse/CAS2-261)
confirm:
Should a release fail at any step, you as the author should now lead …
=> Tweak previous conviction question and answer for no

e2e-tests/steps/assess.ts, e2e-tests/tests/03_assess.spec.ts, integration_tests/pages/apply/submittedApplicationOverviewPage.ts, integration_tests/pages/assess/submittedApplicationOverviewPage.ts, integration_tests/tests/apply/submitted_applications/add_an_application_note.cy.ts, integration_tests/tests/assess/add_an_application_note.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/apply/index.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/data/submittedApplicationClient.test.ts, server/data/submittedApplicationClient.ts, server/i18n/en/errors.json, server/paths/assess.ts, server/routes/apply.ts, server/routes/assess.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/services/submittedApplicationService.test.ts, server/services/submittedApplicationService.ts, server/views/applications/overview.njk, server/views/assess/applications/overview.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-211
Allows an assessor to add a note to a submitted application, provided the NOTES_DISABLED env variable is set to 'false'.
confirm:
=> Feature flagged: allow an assessor to add a note to an application

server/views/partials/layout.njk
https://dsdmoj.atlassian.net/browse/CAS2-120?atlOrigin=eyJpIjoiNTBjMGY3MjJiNGZhNGE4YmFiMDk0OTdjZDRlNDhjZmMiLCJwIjoiaiJ9
- The version 1.12.1 of jquery-ui has security vulnerabilities so we need to take some action. We could bump it but on review of the typescript template this has now been removed [2]. This suggests it’s no longer needed so we take the approach of removing it instead
- As I understand it jquery-ui is a superset of jquery
- The MOJ Frontend (which itself builds on the GOV.UK Frontend) requires jquery to be provisioned by the consumer[1] (us). It does not mention jquery-ui explicitly
[1] https://github.com/ministryofjustice/moj-frontend/blob/main/package/package.json#L34
[2] https://github.com/ministryofjustice/hmpps-template-typescript/commit/14f2b43344ae2ee771e7c70c508b744 …
=> Remove jquery-ui as no longer required

doc/how-to/removing_old_answers_on_an_application.md
This came up today as we discussed implementing another type of this change. We don't have a good way to automate this so it requires a human to remember which risks it being forgotten.
- We could write this in a checklist but it probably doesn't happen enough so we'd likely not notice it on the rare occasion it would be relevant. A similar thing could happen with Jira card checklist
- We could try and automate this somehow by redesigning how the question framework so it requires us to be more explicit about the relationship around dependencies. Such that the adding of the question and it's sub-questions is expressed explicitly so it could be automatically torn down. We're not sure how this would work, it would likely require more time than the couple of months we have left
- document the …
=> Document our approach to removing old answers on the application

e2e-tests/steps/apply.ts, e2e-tests/steps/assess.ts
Because of the way the tests are written, we will likely end up adding notes to the same applications multiple times through the E2E tests. So, we have a double safeguard of checking that the note we have added is first in the list, and also that it is unique.
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-231
confirm:
Should a release fail at any step, you as the …
=> Extend E2E tests to check notes added appear on application timeline

.circleci/config.yml
This follow's CAS1's implementation (and the recommended CircleCI way), and should allow us to see videos of failing tests in CircleCI UI (e.g. [here[1]](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-approved-premises-api/10433/workflows/6da2f46d-345b-43b9-9963-6f9b3981b01f/jobs/32937/artifacts)) helping us debug failures quicker.
=> store test artifacts for e2e's

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-319
Fixes a bug which meant that the 'OASys completed' date wasn't rendering for RoSH data.
confirm:
=> Fix RoSH OASys import date bug

server/utils/applications/utils.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CAS2-308?atlOrigin=eyJpIjoiZTU1NDRkZWU4ZjlkNDA5YWE3YmY2MGQ0Mzg0MDJiYzUiLCJwIjoiaiJ9)
We want application notes that contain linebreaks to preserve this formatting.
confirm:
=> (308) Apply correct formatting for application notes

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
As we have tested this in dev/test and are ready
to release, this turns the feature flag for Notes
off, so that the feature should be displayed to
users.
We will remove the flag in a future PR.
confirm:
=> Turn Notes feature on in preprod/prod

.env.example, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, server/config.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts, server/views/applications/overview.njk, server/views/assess/applications/overview.njk
https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-322
The NOTES_DISABLED flag was put in in order to
incrementally release the Notes/Further Info work.
As we have now released the feature to production,
and we do not plan to hide it again, we can remove
this feature flag.
confirm:
Should a release fail at any step, you as the author …
=> Remove NOTES_DISABLED feature flag

integration_tests/mockApis/submissions.ts, integration_tests/pages/submissions/submissionListPage.ts, integration_tests/tests/assess/view_all_submitted_applications.cy.ts, server/@types/shared/models/Cas2SubmittedApplicationSummary.ts, server/testutils/factories/submittedApplicationSummary.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/assess/applications/index.njk
DO NOT MERGE UNTIL THIS API PR MERGED: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1621, and the first commit pointing to the types branch is deleted.
See above PR for context of this work - TLDR, reading person data on the top level fields of an Application to avoid extra integration API calls.
This changes how we construct the table on the assessors dashboard at `assess/applications`
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofju …
=> Use `personName`, `crn` and `nomsNumber` on assessments dashboard view

feature.env, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/assess/statusUpdateController.test.ts, server/controllers/assess/statusUpdateController.ts, server/controllers/peopleController.test.ts, server/controllers/peopleController.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts, server/utils/validation.test.ts, server/utils/validation.ts, server/utils/viewUtils.test.ts, server/utils/viewUtils.ts, server/views/applications/taskList.njk
[Jira ticket 290](https://dsdmoj.atlassian.net/browse/CAS2-290)
We're currently not validating the `referer` header, which theoretically allows for "Reflected XSS attacks", as a `referer` could be passed in the header of a GET request. Although this is currently blocked by our CSP settings, we've been recommended to fix this by the pen test report.
This introduces a `validateReferer` function that checks the `referer` comes from our own URL, read from the ingress in the config. We've opted to revert to the root URL (`/`) for the back link otherwise.
confirm:
Once we've merged it …
=> (CAS2-290) Validate the referer header used in backlinks and redirects

e2e-tests/steps/offenceAndLicenceInformationSection.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.test.ts, server/form-pages/apply/offence-and-licence-information/current-offences/custom-forms/currentOffenceData.ts, server/form-pages/apply/offence-and-licence-information/offending-history/custom-forms/offenceHistoryData.ts, server/views/applications/pages/current-offences/current-offences.njk
The discrepancy was causing E2E test failures, so I have corrected it in accordance with the up to date designs.
confirm:
=> Change ‘offence category’ text to ‘offence type’

integration_tests/pages/apply/list.ts, integration_tests/pages/apply/prisonDashboard.ts, integration_tests/pages/homePage.ts, integration_tests/tests/apply/dashboard.cy.ts, integration_tests/tests/apply/prison_dashboard.cy.ts, integration_tests/tests/home_page.cy.ts, integration_tests/tests/login.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/paths/apply.ts, server/routes/apply.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts, server/views/applications/index.njk, server/views/applications/prison-dashboard.njk
There is more info in the slack message here:
https://mojdt.slack.com/archives/C04T6SC31HA/p1712920017883269?thread_ts=1712143310.370659&cid=C04T6SC31HA 
Essentially we want to add these things behind the recently introduced feature flag:
1. Sub-nav on referrer's existing applications page to toggle between their applications and applications in their prison
2. a blank page with same sub-nav on it where the prison dashboard will eventually go.
3. A tile on the home page to go directly to the prison dashboard page
This PR introduces most of the boiler plate to add a new route and tile - Content of the page to come in future PR.
I've set the prison dashboard up on a separate route to make things simpler, and because I think it makes sense - it's a subset of applications, and it appears …
=> CAS2-405: Add skeleton prison dashboard tab behind feature flag

integration_tests/tests/apply/dashboard.cy.ts, server/services/applicationService.test.ts, server/testutils/factories/applicationSummary.ts, server/testutils/factories/latestStatusUpdate.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/views/applications/index.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-399
Adds a row to the submitted applications table on the referrer dashboard to show the latest status of the application.
confirm:
=> Show latest status for submitted applications

integration_tests/pages/apply/list.ts, server/testutils/factories/applicationSummary.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts
Ref: JIRA ticket [CAS2-412](https://dsdmoj.atlassian.net/browse/CAS2-412)
This PR contains the work required for the second sub task of [CAS2-401](https://dsdmoj.atlassian.net/browse/CAS2-401)
Tasks:
- UI: start using personName on the applications dashboard
We currently return for ApplicationSummaries a full Person result, which includes a lot of data, and causes issues with how we handle whether the person has been found/is restricted.
We propose that we follow the standard set for /submissions and just return a personName which will be ‘Unknown’ if person not found or restricted.
This will mean we can then do a bulk search with the CRNs more easily, and just get the person’s name.
[CAS2-401]: https://dsdmoj.atlassian.net/browse/CAS2-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> CAS2-412 Start using personName on the applications dashboard

server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.test.ts, server/form-pages/apply/before-you-start/hdc-licence-dates/hdcLicenceDates.ts, server/utils/dateUtils.test.ts, server/utils/dateUtils.ts
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-421
Previously, invalid dates were being passed into isMoreThanMonthsBetweenDates, which was causing errors. This introduces return statements to ensure that empty or invalid dates are returned before those checks.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier-2 …
=> Fix bug with HDC and conditional release date errors

server/views/applications/pages/risk-to-self/current-risk.njk, server/views/applications/pages/risk-to-self/historical-risk.njk
Change question header size for current risk to self and historical risk to self for consistency with other question pages. 
[Jira ticket 430](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A69692b62-eae7-4d24-a8c3-485fff2e20ee&selectedIssue=CAS2-430)
confirm:
Should a release fail at any step, you as the author should now lead the …
=> Change question header size for current and historical risk

assets/scss/components/_side-nav.scss
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-464
On smaller screen displays, this content was layering, making it impossible to read. This media query fixes that.
However, tabbing doesn't provide a very satisfactory experience, because when you hit return on a specific item, you navigate there, but lose your place in the side nav component (so then need to tab all the way through the page to get back to it). This is a preexisting issue and I'm not sure how easy it would be to solve, but if anyone has any ideas, do share them. …
=> Fix content display on review application pages

e2e-tests/steps/apply.ts, e2e-tests/test.ts, e2e-tests/tests/01_apply_as_pom.spec.ts, e2e-tests/tests/02_apply_as_lca.spec.ts, playwright.config.ts
We need to test that our POM and LCA users can view and
add notes to applications on their prison dashboard.
Previously we hardcoded the application ID to be used locally
and in dev environment, because we had a standard
prison for our users across both environments.
Since we now are restricting users to only create applications
for offenders within their own prison, we have discovered that
the example offenders in dev and local have different prisons (LEI for local,
MDI for dev). [1] So our local and dev test users do not have the same prison
any more, and that hardcoded UUID no longer works.
In this commit we use the user's name to find an application by any user
that is not them, thus removing the need for a hardcoded id.
This has the added benefit that it's agnostic to what the seeded …
=> Fix e2e test for adding note via prison dashboard

playwright.config.ts
Using work merged in this AP Tools PR: https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/67
We will shortly be restricting referrer
permissions to only create applications for
offenders within the same prison. The previous
nomsNumber used here did not have prison data, and a new one has been added in AP Tools with more
detail here:
https://github.com/ministryofjustice/hmpps-approved-premises-tools/pull/67s
=> update 'no Oasys' nomsNumber

integration_tests/mockApis/applications.ts, integration_tests/pages/apply/prisonDashboard.ts, integration_tests/tests/apply/prison_dashboard.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/paths/apply.ts, server/services/applicationService.test.ts, server/services/applicationService.ts, server/views/applications/prison-dashboard.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-409
Adds pagination to the prison dashboard view.
confirm:
=> Paginate applications on the prison dashboard page

e2e-tests/pages/apply/dashboardPage.ts, e2e-tests/steps/apply.ts, integration_tests/tests/home_page.cy.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts
Update content to:
- make language consistent with rest of the service where we generally use "application" instead of "referrer" 
- make it clearer which applications you are viewing now that prison applications are viewable
[Jira ticket 433](https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?selectedIssue=CAS2-433)
confirm:
Should a release fail at …
=> Update content to use application instead of referral

server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/disability.ts
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-76
Fixes bug that was causing the page to error when the user selected 'yes' and then 'other' disability, without entering anything in the free text field, and then changed the top level answer to 'no'.
confirm:
=> Fix bug on disability page

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/oldOasys.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/oldOasys.ts, server/form-pages/apply/risks-and-needs/risk-to-self/oldOasys.test.ts, server/form-pages/apply/risks-and-needs/risk-to-self/oldOasys.ts
This was previously omitted, causing a bug for users.
confirm:
=> Add date validation on old oasys form pages

e2e-tests/test.ts
For the dev environment tests. The previous details were for an offender with no
prison info [1] Now that we are checking the
offender's prison [2] this prison data is required to proceed.
[1] https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4467949648/CRNs+for+Testing+in+Development+Environment
[2] https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1877
Can be tested on the dev environment by using this noms number to create an application.
=> Use offender details with prison for 'no oasys' e2e

package-lock.json, package.json, renovate.json
Rollback app insights to fix log aggregration.
* It was reported that our applications were no longer correctly sending logs through to App Insights[0]. It appears as though upgrading to v3 has stopped attaching the services’ role name to our metrics, this makes it hard/impossible to aggregate from within App Insights. Until this has been fixed on a MoJ compatible way, we roll back to a safe version.
* Renovate automatically suggested this update on 19th April[1], from which time our logs have been inadvertently broken
* The Typescript template (which we are based on) has had this rollback applied [2]
* CAS1 has already rolled back[3]
[0] https://mojdt.slack.com/archives/C03K0HB0LBE/p1716222154095039
[1] https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/commit/5e …
=> [489] Fix application insights log aggregation by rolling back to v2

server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/pages/confirm-consent/confirm-consent.njk, server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk, server/views/applications/pages/hdc-licence-dates/hdc-licence-dates.njk
Jira ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CAS2/boards/1347?assignee=712020%3A23fbf793-ee9a-4ecd-ad4d-37beaa0edeaa&selectedIssue=CAS2-123
Bug fix for the back buttons on the pages a user completes after creating an application but before reaching the task list.
This change ensures that for the confirm eligibility page, no back button will render when it is accessed prior to reaching the task list. This makes sense as continuing from the previous page has completed the irreversible step of creating a new application.
For the confirm consent and HDC pages, the back buttons will point to confirm eligibility and confirm consent, respectively.
ready to be released at any point. Before merging …
=> Fix back buttons for pre-task list pages

server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.test.ts, server/form-pages/apply/about-the-person/equality-diversity-monitoring/religion.ts
This ensures that the back button will direct the user back to the correct ethnic background page, depending on the answer they have given.
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-343
confirm:
=> Fix back links from religion page

e2e-tests/steps/risksAndNeedsSection.ts
After updating the risk to self task, the h1 for the ‘additional information’ page has changed.
confirm:
=> Fix risk to self E2E test

integration_tests/mockApis/applications.ts, integration_tests/tests/apply/submitted_applications/add_an_application_note.cy.ts, integration_tests/tests/assess/add_an_application_note.cy.ts, server/@types/shared/models/MigrationJobType.ts, server/@types/shared/models/SituationOption.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/assess/submittedApplicationsController.test.ts, server/controllers/assess/submittedApplicationsController.ts, server/data/submittedApplicationClient.test.ts, server/data/submittedApplicationClient.ts, server/paths/api.ts, server/views/applications/overview.njk, server/views/assess/applications/overview.njk
This is the second part of the work to repoint notes to assessments and is described in more detail here:
https://dsdmoj.atlassian.net/wiki/spaces/AP/pages/4897341539/Associate+Application+Notes+with+Assessments+CAS2-327
The work is to change the front end to use the `/assessments/{assessmentId}/notes` endpoint instead of the `/submissions/{applicationId}/notes` endpoint.
1. Update types.
2. Add path to add note via assessments.
3. Update views to pass assessment and application ids. 
4. Change api path to use /assessments/{assessmentId}/notes. 
5. Update client to use new assessments endpoint. 
6. Update addNote() for apply route to use assessmentId. 
7. Update addNote() for assess route to use assessmentId. 
8. Update integration tests in accordance with updated addNote(). 
As part of …
=> Cas2 327 repoint notes to assessments part 2

server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts, server/views/people/partials/personDetails.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-236
As above. Arguably there are other person fields that we should do the same with, but I've limited this to nationality based on what has been flagged.
confirm:
=> Display nationality as "Unknown" when it is not present in person definition

server/views/applications/index.njk, server/views/applications/prison-dashboard.njk, server/views/assess/applications/index.njk, server/views/partials/applicationSoftDeleteGuidance.njk
This guidance explains to users which applications will no longer appear on this dashboard due to API filtering.
Not to be merged until the following is in: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1891.
Jira ticket: https://dsdmoj.atlassian.net/browse/CAS2-434
confirm:
Should a release fail at any step, you as the author should now lead the …
=> Add prison dashboard soft delete guidance

e2e-tests/steps/apply.ts, e2e-tests/steps/cancelInProgressApplication.ts, e2e-tests/tests/01_apply_as_pom.spec.ts
This fixes currently failing e2es on the dev environment for cancelling an Application. 
Previously this test just chose the last in progress application to cancel, by looking for the last `Cancel` anchor tag.
This meant that depending on the state of applications in the database the name of the person on the application could have been anything, and we need to assert that the page is showing the applicant's name in the header.
This changes the test to create an in progress application for our standard person, to ensure there will always be a most recent application for that person first in the list, and then selects that application row to cancel it.
[Find the …
=> CAS2: Fix cancel application e2e's

integration_tests/pages/apply/applicationSubmittedPage.ts, integration_tests/tests/apply/submit.cy.ts, server/utils/nunjucksSetup.ts, server/utils/phaseBannerUtils.test.ts, server/utils/phaseBannerUtils.ts, server/views/applications/confirm.njk, server/views/partials/header.njk, server/views/static/accessibility-statement.njk
The URL for the satisfaction/feedback survey is now extracted into an exported constant to ensure it can be easily updated service-wide.
https://dsdmoj.atlassian.net/browse/CAS-435
Updates the URL for the external feedback form.
The URL is now exported from a new `PhaseBannerUtils` file, which also exports the support email -- this ensures any updates to either of these can be applied service-wide easily.
confirm:
[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/ …
=> CAS-435: Update URL to satisfaction survey

.circleci/config.yml
This PR reinstates Slack alerts on CI E2E test failures, and updates the alert channel to the shared `#cas-events`
=> CHORE: e2e failures slack alerts

.circleci/config.yml
This job does not provide any useful output beyond what the npm security audit does. The maintainers of the Typescript template have now removed it from the template itself [1]
[1] https://github.com/ministryofjustice/hmpps-template-typescript/pull/388
=> Remove check_outdated job

playwright.config.ts
If the test fails in CI we want to be able to playback the trace and/or video in order to better understand what went wrong.
=> Retain trace and video on E2E test failure

.github/workflows/generate-types.yml
This prevents polluting the PRs on GitHub with a new PR with every type generation action. Instead the same PR gets incremental changes, removing the need to manually close obsolete PRs.
This was done for CAS3 in https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/pull/951
=> CHORE: Use single branch and PR for types generation

server/views/partials/applicationSoftDeleteGuidance.njk
Ref: https://dsdmoj.atlassian.net/browse/CAS2-505
Applications where the status is withdrawn, cancelled or awaiting arrival and created greater than 32 days in the past can be excluded from the applications list (previously 14 days).
Related API PR: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/2173
=> CAS2-505 Change filter note from 14 to 32 days.

server/views/applications/pages/current-offences/current-offences.njk, server/views/applications/pages/risk-to-self/acct.njk
https://dsdmoj.atlassian.net/browse/CAS2-452
"remove was being read out twice for screen reader users because the visual text is "Remove" and then  repeated again in the visually hidden text. Although not mentioned in the audit report screenreader users would struggle to navigate the links if there were multiple links with the same text but taking them to different pages. I've tried to improve it by giving more context to the Remove link in the visually hidden text and will double check with content design
No visual differences for the user.
=> improve "Remove" links

server/form-pages/apply/area-and-funding/funding-information/alternativeID.test.ts, server/form-pages/apply/area-and-funding/funding-information/alternativeID.ts, server/views/applications/pages/funding-information/alternative-identification.njk
https://dsdmoj.atlassian.net/browse/CAS2-455
The alternative funding checkboxes were not linked to the page heading. I've fixed this now but I've not addressed the other accessibility/ux issues which the audit mentioned like repeating the hint text multiple times. I think linking the checkboxes to the page heading is a huge improvement but anything else like splitting the page up into multiple pages or multiple fieldsets really needs design/content input.
No visual changes
confirm: …
=> Funding ID checkboxes are not linked to the context

integration_tests/pages/page.ts, server/views/partials/documentSummaryList.njk
https://dsdmoj.atlassian.net/browse/CAS-951
Before the summary cards heading levels where level 2 which is the same as their section headings which is not logical. This change makes the summary card heading level 3 to show that they smaller sections within their section.
```
<h1>Check Catherine Hettinger's Application</h1>
<h2>Contents</h2>
<h2>Application Details</h2>
<h2>Before you apply</h2>
<h3>Confirm Eligibility</h3>
<h3>Confirm consent to share information</h3>
```
There are no visual changes
confirm:
[Find …
=> Fix heading levels for section summary cards

server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts, server/views/applications/show.njk, server/views/people/confirm-applicant-details.njk
https://dsdmoj.atlassian.net/browse/CAS-945
On the "Check your answers" page theres a "Download to PDF" button which uses the browsers print functionality and the user can "Save as a pdf". This page contains a lot of "Change" links against a LONG list of summary list items. These links have been raised as an accessibility issue. Instead of implementing a server side generated PDF, we have decided to hide the change links from printed/pdf media as there is no need for the change links once the application has been downloaded/printed.
Small sample of page
confirm:
Once we've merged …
=> CAS-945 Hide "Change" links when "Download as PDF" or printing

integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, server/views/components/sideNav/macro.njk
https://dsdmoj.atlassian.net/browse/CAS-950
In the sidebar, we have a long list of navigation items and the last one says "Back to top". Currently it sets the viewport to the top of page but does not focus any element. There is no anchor point with an id of `top` which is why the viewport takes the user to the top instead of top of the navigation list.
This commit ensures that the first link in the sidebar will now have an id of `top` which the `Back to top` can go to and focus the user on.
https://github.com/user-attachments/assets/38413c25-4dc5-434d-bc49-8948c0e4f9ba
https://github.com/user-attachments/assets/5790929e-ab8c-4fa5-877f-8b4292ad81f6
ready to be released at any point. Before merging to `main` we …
=> CAS-950 Make the first nav link focusable for "back to top"

e2e-tests/tests/01_apply_as_pom.spec.ts
There was a flickering spec where the tests expect there to be no other data.
What seems to be happening is that the selectors playwirght was using was including results from "Submitted" as they are on the page but are visually hidden. The selector was also including the table headings.
Should fix this https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-approved-premises-api/22091/workflows/d70862cc-3b23-479f-8f3c-9fb80e7fdd2d/jobs/101250
```
1) [dev] › 01_apply_as_pom.spec.ts:68:5 › cancel an in progress application from the task list ───
Error: expect(received).toEqual(expected) // deep equality
Expected: 1
Received: 11
75 |   const numberOfApplicationsAfterCancellation = (await page.locator('tr').all()).length
76 |   await expect(page.getByText('Your CAS-2 …
```
=> Improve e2e tests

server/@types/ui/index.d.ts, server/utils/applications/utils.test.ts, server/utils/applications/utils.ts
https://dsdmoj.atlassian.net/browse/CAS-1347
Caused by changes introduced in https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/845
For user notes, we automatically format their paragraphs. Using MOJ timeline text attribute meant that nunjucks would escape html tags and replace them with HTML entries. It should be noted that the actual users notes is escaped before being processed so there is no risk of a potential XSS attack
confirm: …
=> BUG Timeline entries not correctly formatted

server/data/applicationClient.test.ts
**PR changes:**
* Fix for pact tests 
* caused by changes made to move to child object `CAS2Application` n this BE PR: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/3053/files#diff-be6259540a0a2641596f6c3be134afc25cc99d0242980dd8b0ea475eeb6074e9
=> Fixes for application-client pact issues

integration_tests/pages/apply/risks_and_needs/risk-of-serious-harm/manualRoshInformationPage.ts, integration_tests/pages/apply/risks_and_needs/risk-of-serious-harm/oldOasysPage.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/manual_rosh_information.cy.ts, integration_tests/tests/apply/risks_and_needs/risk-of-serious-harm/old_oasys.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/index.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/oldOasys.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/oldOasys.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/summary.ts, server/form-pages/utils/index.ts, server/form-pages/utils/questions.ts, server/i18n/en/errors.json, server/views/applications/pages/risk-of-serious-harm/manual-rosh-information.njk
Adds a new journey to "Create an application" process. If the POM selects, 'No' to the `Does offender have an older OASys with risk of serious harm (RoSH) information?`, they will be taken to a new page where they will fill in the manual rosh data themselves. The rest of the process is exactly the same and the RoSH summary table should return the data that was entered.
OUT OF SCOPE: Updating "Check your answers" before submitting the application. this will be done as a separate PR.
confirm:
[Find the …
=> CAS-1221: Add Manual RoSH Information to application

integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, integration_tests/tests/apply/check_your_answers/check_your_answers.cy.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/custom-forms/manualRoshInformation.ts
`JIRA`: https://dsdmoj.atlassian.net/browse/CAS-1478
* Display the manually entered RoSH data on the 'Check your answers' page
* Unit test coverage
* Integration test coverage
confirm:
=> Display Manual RoSH data in 'Check your answers' page

e2e-tests/testOptions.ts, playwright.config.ts
* Fix for "create a CAS-2 application with no OASys" local e2e test
* Change personWithoutOasys user to Teresa Green
* Create new personWithLaoRestrictions and set them to James Brown
=> Fix for "create a CAS-2 application with no OASys" local e2e test:

.circleci/config.yml, package.json
Theres jobs are now run using GH Actions (https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/pull/901)
It was discovered as part of this work that the splitting of the tests were not configured correctly and running all the tests 4 times. This was because we hadn't passed the TEST_ARG env var to the calling npm script. The 94 specs are now ~25 tests being run in each CI node.
=> Remove unit/integration tests, linting from CircleCI

.github/workflows/security_npm_dependency.yml
This ensures the NPM dependency security check uses a node version file that exists, rather than relying on the default `.nvmrc` which isn't present in this repository.
=> Specify node version file

.github/actions/slack_failure_notification/action.yml
This adds a reusable action which can be used to notify of failure for any job. The actions from the HMPPS Github Actions repository are a bit over the top, so we've created our own.
=> Add Slack notification for E2E failure

server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts
JIRA: https://dsdmoj.atlassian.net/browse/CAS-1594
- always use the `allocatedPomName` value  on the `CAS2Application` in the "Application Owner" column (instead of the `createdByUserName` value)
confirm:
=> Fix in Allocated Applications - Application owner was showing wrong name

helm_deploy/hmpps-community-accommodation-tier-2-ui/values.yaml
This should fix the failed deployment: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/actions/runs/14728190892/job/41338147167
Note: SRE will be adding this to the guidance on moving to Github Actions.
=> Switch to fetching image to ghcr.io for deployment

helm_deploy/hmpps-community-accommodation-tier-2-ui/values.yaml
Container registry was updated to `ghcr.io` but path to organisation was still incorrect 🤦‍♂️ ... This now matches the path used for other CAS UIs:
- CAS1: https://github.com/ministryofjustice/hmpps-approved-premises-ui/blob/main/helm_deploy/hmpps-approved-premises-ui/values.yaml#L8
- CAS3: https://github.com/ministryofjustice/hmpps-temporary-accommodation-ui/blob/main/helm_deploy/hmpps-temporary-accommodation-ui/values.yaml#L9
=> Fix container registry path

integration_tests/mockApis/applications.ts, integration_tests/tests/apply/cancel_in_progress_application.cy.ts, integration_tests/tests/apply/dashboard.cy.ts, integration_tests/tests/apply/prison_dashboard.cy.ts, server/controllers/apply/applicationsController.ts, server/data/applicationClient.test.ts, server/data/applicationClient.ts, server/services/applicationService.test.ts, server/services/applicationService.ts
* Found a bug where `Your applications` > `Submitted` is pulling through all applications for your prison (not just "Your applications"). 
* Bug created by me - sorry! - by misinterpreting requirements on this ticket: https://dsdmoj.atlassian.net/browse/CAS-1629
* The `Before` screenshot below is what we see on `DEV` env currently. 
* The `After` screenshot below is what we now see on my `LOCAL` env (my `LOCAL` env is integrated with the `DEV` env API - so pulling data from same datasource)
* The above `LOCAL UI -> DEV API` configuration means we can trust the before and after data comparison (as LOCAL env and DEV env are pointed at the same datasource). 
* Notice on the `After` screenshot below that we only see their submitted applications only (not all submitted applications under their …
=> Bug Fix for assignment-type params being sent to get CAS2 applications

.github/workflows/deploy_to_test.yml
This stops the 'Deploy to test' docker build from tagging the image as `latest`.
All parts of the deployment processes require a specific version, so no image with the tag `latest` is ever deployed to any of the environments.
Ref: https://github.com/ministryofjustice/hmpps-github-actions/blob/54d81a8b849a002c39a07f7e555562f259c3b22b/.github/workflows/docker_build.yml#L18
=> Stop test deployments from tagging image as latest

Dockerfile
This addresses Dockerfile-related warnings found during docker builds:
=> Suppress Dockerfile syntax warnings

.github/workflows/test.yml
As per the Shellcheck readme [0].
[0] https://github.com/gunar/shellcheck?tab=readme-ov-file#usage
=> CHORE: Add GITHUB_TOKEN to action env to avoid rate limit
